{"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/clearTracker(_:error:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearTracker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tracker","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"tracker","content":[{"type":"paragraph","inlineContent":[{"text":"Tracker handle to free (","type":"text"},{"code":"HTracker","type":"codeVoice"},{"type":"text","text":" as "},{"type":"codeVoice","code":"int64_t"},{"type":"text","text":")."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Populated on unexpected failure (usually unused; SDK clear often returns void)."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"FRBridgeReturnCode."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Clear tracker."}],"metadata":{"symbolKind":"method","externalID":"c:objc(cs)YEOFRBridge(cm)clearTracker:error:","role":"symbol","title":"clearTracker(_:error:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearTracker:error:"}],"modules":[{"name":"YEOFR"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearTracker","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"}],"roleHeading":"Type Method"},"variants":[{"paths":["\/documentation\/yeofr\/yeofrbridge\/cleartracker(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/yeofrbridge\/cleartracker(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/clearTracker(_:error:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearTracker"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier","text":"FRBridgeReturnCode"}],"url":"\/documentation\/yeofr\/yeofrbridge\/cleartracker(_:error:)","title":"clearTracker(_:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/clearTracker(_:error:)","kind":"symbol","role":"symbol","abstract":[{"text":"Clear tracker.","type":"text"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearTracker:error:"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"title":"FRBridgeReturnCode","kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRBridgeReturnCode"}],"navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOFRBridge"}],"url":"\/documentation\/yeofr\/yeofrbridge","title":"YEOFRBridge","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"YEOFRBridge"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"clearTracker:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearTracker:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"FRBridgeReturnCode","kind":"typeIdentifier","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"},{"text":") ","kind":"text"},{"text":"clearTracker:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t"},{"text":") ","kind":"text"},{"text":"tracker","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" **) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"tracker","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tracker handle to free ("},{"type":"codeVoice","code":"HTracker"},{"type":"text","text":" as "},{"type":"codeVoice","code":"int64_t"},{"type":"text","text":")."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Populated on unexpected failure (usually unused; SDK clear often returns void)."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"FRBridgeReturnCode.","type":"text"}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"clearTracker:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1clearTracker(_:error:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearTracker:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1clearTracker(_:error:)\/fragments"},{"value":"FRBridgeReturnCode","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle"},{"value":"YEOFRBridge","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title"},{"value":[{"kind":"identifier","text":"YEOFRBridge"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments"},{"value":[{"kind":"identifier","text":"YEOFRBridge"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}