{"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configure(withThreads:internalResizeWidth:detectionThreshold:error:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"abstract":[{"text":"Configure global SDK parameters.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withThreads"},{"kind":"text","text":" "},{"kind":"internalParam","text":"threads"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"internalResizeWidth"},{"kind":"text","text":" "},{"kind":"internalParam","text":"resizeWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionThreshold"},{"kind":"text","text":" "},{"kind":"internalParam","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode"}],"languages":["swift"]}]},{"parameters":[{"name":"threads","content":[{"type":"paragraph","inlineContent":[{"text":"Number of threads for the SDK to use.","type":"text"}]}]},{"name":"resizeWidth","content":[{"type":"paragraph","inlineContent":[{"text":"Internal resize width for detection (see vendor docs).","type":"text"}]}]},{"name":"threshold","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Detection threshold (higher is stricter)."}]}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"Populated on failure with an NSError describing the SDK error."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"FRSDKReturnCode.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Applies common global knobs such as thread count and detection parameters.","type":"text"},{"text":" ","type":"text"},{"text":"Call this early (e.g., after activation) and whenever configuration changes.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/configure(withthreads:internalresizewidth:detectionthreshold:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/configure(withthreads:internalresizewidth:detectionthreshold:error:)"]}],"metadata":{"title":"configure(withThreads:internalResizeWidth:detectionThreshold:error:)","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"YEOFR"}],"navigatorTitle":[{"kind":"identifier","text":"configureWithThreads:internalResizeWidth:detectionThreshold:error:"}],"externalID":"c:objc(cs)YEOFRBridge(cm)configureWithThreads:internalResizeWidth:detectionThreshold:error:","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withThreads"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"internalResizeWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode"}]},"kind":"symbol","references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frsdkreturncode","abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","kind":"symbol","title":"FRSDKReturnCode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"role":"symbol","title":"YEOFRBridge","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOFRBridge"}],"type":"topic","url":"\/documentation\/yeofr\/yeofrbridge","navigatorTitle":[{"kind":"identifier","text":"YEOFRBridge"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"type":"topic","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"url":"\/documentation\/yeofr","title":"YEOFR","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/configure(withThreads:internalResizeWidth:detectionThreshold:error:)":{"url":"\/documentation\/yeofr\/yeofrbridge\/configure(withthreads:internalresizewidth:detectionthreshold:error:)","abstract":[{"type":"text","text":"Configure global SDK parameters."}],"role":"symbol","title":"configure(withThreads:internalResizeWidth:detectionThreshold:error:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"text":"withThreads","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"internalResizeWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"configureWithThreads:internalResizeWidth:detectionThreshold:error:","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configure(withThreads:internalResizeWidth:detectionThreshold:error:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"configureWithThreads:internalResizeWidth:detectionThreshold:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"configureWithThreads:internalResizeWidth:detectionThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"},{"kind":"text","text":") "},{"kind":"identifier","text":"configureWithThreads:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int32_t","preciseIdentifier":"c:@T@int32_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"threads"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalResizeWidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int32_t","text":"int32_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"resizeWidth"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int32_t","text":"int32_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"threshold"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Number of threads for the SDK to use.","type":"text"}]}],"name":"threads"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Internal resize width for detection (see vendor docs).","type":"text"}]}],"name":"resizeWidth"},{"content":[{"inlineContent":[{"text":"Detection threshold (higher is stricter).","type":"text"}],"type":"paragraph"}],"name":"threshold"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Populated on failure with an NSError describing the SDK error.","type":"text"}]}],"name":"error"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"FRSDKReturnCode.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","op":"replace","value":"FRSDKReturnCode"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","op":"replace","value":[{"text":"FRSDKReturnCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","op":"replace","value":"YEOFRBridge"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","op":"replace","value":[{"kind":"identifier","text":"YEOFRBridge"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"YEOFRBridge"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1configure(withThreads:internalResizeWidth:detectionThreshold:error:)\/title","op":"replace","value":"configureWithThreads:internalResizeWidth:detectionThreshold:error:"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1configure(withThreads:internalResizeWidth:detectionThreshold:error:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"configureWithThreads:internalResizeWidth:detectionThreshold:error:","kind":"identifier"}]}]}]}