{"metadata":{"title":"createTracker(_:error:)","roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"createTracker:error:","kind":"identifier"}],"externalID":"c:objc(cs)YEOFRBridge(cm)createTracker:error:","modules":[{"name":"YEOFR"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createTracker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":">, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"text":") -> ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode"}]},"variants":[{"paths":["\/documentation\/yeofr\/yeofrbridge\/createtracker(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/yeofrbridge\/createtracker(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/createTracker(_:error:)"},"abstract":[{"type":"text","text":"Create a new tracker."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createTracker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"outTracker","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":">, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"text":") -> ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"typeIdentifier","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"}]}]},{"parameters":[{"name":"outTracker","content":[{"inlineContent":[{"text":"On success, receives the newly created tracker handle (","type":"text"},{"type":"codeVoice","code":"HTracker"},{"text":" as ","type":"text"},{"type":"codeVoice","code":"int64_t"},{"text":").","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"Populated on failure with an NSError describing the SDK error.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"FRBridgeReturnCode.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/createTracker(_:error:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTracker"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier","text":"FRBridgeReturnCode"}],"url":"\/documentation\/yeofr\/yeofrbridge\/createtracker(_:error:)","title":"createTracker(_:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/createTracker(_:error:)","kind":"symbol","role":"symbol","abstract":[{"text":"Create a new tracker.","type":"text"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTracker:error:"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOFRBridge"}],"url":"\/documentation\/yeofr\/yeofrbridge","title":"YEOFRBridge","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"YEOFRBridge"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"title":"FRBridgeReturnCode","kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRBridgeReturnCode"}],"navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"createTracker:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createTracker:error:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"createTracker:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@int64_t","text":"int64_t","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"outTracker","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" **) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On success, receives the newly created tracker handle ("},{"type":"codeVoice","code":"HTracker"},{"type":"text","text":" as "},{"type":"codeVoice","code":"int64_t"},{"type":"text","text":")."}]}],"name":"outTracker"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Populated on failure with an NSError describing the SDK error."}]}],"name":"error"}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"FRBridgeReturnCode."}],"type":"paragraph"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1createTracker(_:error:)\/title","value":"createTracker:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1createTracker(_:error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createTracker:error:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","value":"YEOFRBridge","op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","value":[{"text":"YEOFRBridge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","value":[{"text":"YEOFRBridge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode","op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}