{"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/extractreferencetemplate(inbuffer:width:height:scanline:tracker:faceid:legacybgra:outtemplate:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/extractreferencetemplate(inbuffer:width:height:scanline:tracker:faceid:legacybgra:outtemplate:error:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"extractReferenceTemplateInBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:","kind":"identifier"}],"modules":[{"name":"YEOFR"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extractReferenceTemplate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inBuffer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SV","kind":"typeIdentifier","text":"UnsafeRawPointer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanLine"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracker"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"legacyBGRA"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outTemplate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":"?>?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"text":") -> ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode"}],"role":"symbol","title":"extractReferenceTemplate(inBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:)","symbolKind":"method","roleHeading":"Type Method","externalID":"c:objc(cs)YEOFRBridge(cm)extractReferenceTemplateInBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:"},"abstract":[{"type":"text","text":"Extract an "},{"type":"codeVoice","code":"FSDK_FaceTemplate"},{"type":"text","text":" for one currently-tracked face, to be retained as an enrolment"},{"type":"text","text":" "},{"type":"text","text":"reference and later passed back to "},{"type":"codeVoice","code":"processFrameWithBuffer:…referenceTemplate:"},{"type":"text","text":" for graded matching."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extractReferenceTemplate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inBuffer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SV","kind":"typeIdentifier","text":"UnsafeRawPointer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanLine"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracker"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"legacyBGRA"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outTemplate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","text":"FRBridgeReturnCode"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Must match the colour order used for the gallery this template joins (see"},{"text":" ","type":"text"},{"code":"processFrameWithBuffer:","type":"codeVoice"},{"type":"text","text":"): NO permutes to RGBA, YES feeds verbatim BGRA. Mixing"},{"type":"text","text":" "},{"type":"text","text":"orders within one bank would make templates incomparable."}]}],"name":"legacyBGRA"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On success, receives raw "},{"type":"codeVoice","code":"FSDK_FaceTemplate"},{"type":"text","text":" bytes (fixed size)."}]}],"name":"outTemplate"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"FRBridgeReturnCode."}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Loads + mirrors the buffer identically to "},{"type":"codeVoice","code":"processFrameWithBuffer:"},{"type":"text","text":" (so tracker-space facial features"},{"type":"text","text":" "},{"type":"text","text":"align with the image), reads the tracked face’s features via "},{"type":"codeVoice","code":"FSDK_GetTrackerFacialFeatures"},{"type":"text","text":", then"},{"type":"text","text":" "},{"type":"codeVoice","code":"FSDK_GetFaceTemplateUsingFeatures"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/extractReferenceTemplate(inBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:)","interfaceLanguage":"swift"},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOFRBridge"}],"url":"\/documentation\/yeofr\/yeofrbridge","title":"YEOFRBridge","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"YEOFRBridge"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/extractReferenceTemplate(inBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"extractReferenceTemplate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SV","text":"UnsafeRawPointer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scanLine","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"tracker","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"legacyBGRA","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"outTemplate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"NSErrorPointer","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/extractReferenceTemplate(inBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:)","title":"extractReferenceTemplate(inBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"extractReferenceTemplateInBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"Extract an "},{"type":"codeVoice","code":"FSDK_FaceTemplate"},{"type":"text","text":" for one currently-tracked face, to be retained as an enrolment"},{"type":"text","text":" "},{"type":"text","text":"reference and later passed back to "},{"type":"codeVoice","code":"processFrameWithBuffer:…referenceTemplate:"},{"type":"text","text":" for graded matching."}],"role":"symbol","url":"\/documentation\/yeofr\/yeofrbridge\/extractreferencetemplate(inbuffer:width:height:scanline:tracker:faceid:legacybgra:outtemplate:error:)","kind":"symbol","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"title":"FRBridgeReturnCode","kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRBridgeReturnCode"}],"navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"extractReferenceTemplateInBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"extractReferenceTemplateInBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","text":"FRBridgeReturnCode"},{"kind":"text","text":") "},{"kind":"identifier","text":"extractReferenceTemplateInBuffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"width:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"int"},{"kind":"text","text":") "},{"kind":"internalParam","text":"width"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"int"},{"kind":"text","text":") "},{"kind":"internalParam","text":"height"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanLine:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"int"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scanLine"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracker:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier","text":"int64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tracker"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceID:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier","text":"int64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"faceID"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacyBGRA:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"legacyBGRA"},{"kind":"text","text":" "},{"kind":"identifier","text":"outTemplate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" **) "},{"kind":"internalParam","text":"outTemplate"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" **) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Must match the colour order used for the gallery this template joins (see","type":"text"},{"text":" ","type":"text"},{"code":"processFrameWithBuffer:","type":"codeVoice"},{"text":"): NO permutes to RGBA, YES feeds verbatim BGRA. Mixing","type":"text"},{"text":" ","type":"text"},{"text":"orders within one bank would make templates incomparable.","type":"text"}]}],"name":"legacyBGRA"},{"content":[{"type":"paragraph","inlineContent":[{"text":"On success, receives raw ","type":"text"},{"code":"FSDK_FaceTemplate","type":"codeVoice"},{"text":" bytes (fixed size).","type":"text"}]}],"name":"outTemplate"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"FRBridgeReturnCode."}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","value":"YEOFRBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","value":[{"text":"YEOFRBridge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","value":[{"text":"YEOFRBridge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1extractReferenceTemplate(inBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:)\/title","value":"extractReferenceTemplateInBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1extractReferenceTemplate(inBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"extractReferenceTemplateInBuffer:width:height:scanLine:tracker:faceID:legacyBGRA:outTemplate:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]}]}]}