{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLicenseInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"outLicenseInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"On success, receives a human-readable license string. Nil on failure."}],"type":"paragraph"}],"name":"outLicenseInfo"},{"content":[{"inlineContent":[{"type":"text","text":"Populated on failure with an NSError describing the SDK error."}],"type":"paragraph"}],"name":"error"}]},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"FRSDKReturnCode."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"metadata":{"symbolKind":"method","modules":[{"name":"YEOFR"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLicenseInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getLicenseInfo:error:"}],"title":"getLicenseInfo(_:error:)","role":"symbol","externalID":"c:objc(cs)YEOFRBridge(cm)getLicenseInfo:error:"},"sections":[],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getLicenseInfo(_:error:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Retrieve license information from the SDK (optional)."}],"variants":[{"paths":["\/documentation\/yeofr\/yeofrbridge\/getlicenseinfo(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/yeofrbridge\/getlicenseinfo(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/getLicenseInfo(_:error:)":{"title":"getLicenseInfo(_:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLicenseInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":"?>?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"}],"url":"\/documentation\/yeofr\/yeofrbridge\/getlicenseinfo(_:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getLicenseInfo(_:error:)","abstract":[{"type":"text","text":"Retrieve license information from the SDK (optional)."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"getLicenseInfo:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"url":"\/documentation\/yeofr\/yeofrbridge","navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"YEOFRBridge"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","kind":"symbol","title":"YEOFRBridge","abstract":[],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"type":"topic","title":"YEOFR","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"FRSDKReturnCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","url":"\/documentation\/yeofr\/frsdkreturncode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"getLicenseInfo:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getLicenseInfo:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"FRSDKReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"getLicenseInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" **) ","kind":"text"},{"text":"outLicenseInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" **) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"outLicenseInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On success, receives a human-readable license string. Nil on failure."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Populated on failure with an NSError describing the SDK error."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"FRSDKReturnCode.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"getLicenseInfo:error:","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getLicenseInfo(_:error:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"getLicenseInfo:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getLicenseInfo(_:error:)\/fragments","op":"replace"},{"value":"YEOFRBridge","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","op":"replace"},{"value":[{"text":"YEOFRBridge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","op":"replace"},{"value":[{"text":"YEOFRBridge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","op":"replace"},{"value":"FRSDKReturnCode","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","op":"replace"},{"value":[{"text":"FRSDKReturnCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","op":"replace"},{"value":[{"text":"FRSDKReturnCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}