{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getTrackerData(_:outData:error:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/gettrackerdata(_:outdata:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/gettrackerdata(_:outdata:error:)"]}],"abstract":[{"text":"Get the current tracker as an in-memory blob.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTrackerData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tracker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tracker handle ("},{"type":"codeVoice","code":"HTracker"},{"type":"text","text":" as "},{"type":"codeVoice","code":"int64_t"},{"type":"text","text":")."}]}],"name":"tracker"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On success, receives NSData containing the serialized tracker."}]}],"name":"outData"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Populated on failure with an NSError describing the SDK error."}]}],"name":"error"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"FRBridgeReturnCode.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Use this to persist the tracker (e.g., write ","type":"text"},{"type":"codeVoice","code":"outData"},{"type":"text","text":" to file or upload)."}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTrackerData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"}],"roleHeading":"Type Method","externalID":"c:objc(cs)YEOFRBridge(cm)getTrackerData:outData:error:","modules":[{"name":"YEOFR"}],"symbolKind":"method","title":"getTrackerData(_:outData:error:)","role":"symbol","navigatorTitle":[{"kind":"text","text":"+ "},{"text":"getTrackerData:outData:error:","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","type":"topic","title":"YEOFR","role":"collection","url":"\/documentation\/yeofr","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"title":"FRBridgeReturnCode","role":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"abstract":[],"title":"YEOFRBridge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"url":"\/documentation\/yeofr\/yeofrbridge","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/getTrackerData(_:outData:error:)":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getTrackerData(_:outData:error:)","role":"symbol","url":"\/documentation\/yeofr\/yeofrbridge\/gettrackerdata(_:outdata:error:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"getTrackerData:outData:error:","kind":"identifier"}],"title":"getTrackerData(_:outData:error:)","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTrackerData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":"?>?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier"}],"abstract":[{"text":"Get the current tracker as an in-memory blob.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getTrackerData:outData:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"getTrackerData:outData:error:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"getTrackerData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@int64_t","text":"int64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"tracker","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" **) ","kind":"text"},{"text":"outData","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" **) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Tracker handle (","type":"text"},{"code":"HTracker","type":"codeVoice"},{"text":" as ","type":"text"},{"code":"int64_t","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}],"name":"tracker"},{"content":[{"inlineContent":[{"text":"On success, receives NSData containing the serialized tracker.","type":"text"}],"type":"paragraph"}],"name":"outData"},{"content":[{"inlineContent":[{"text":"Populated on failure with an NSError describing the SDK error.","type":"text"}],"type":"paragraph"}],"name":"error"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"FRBridgeReturnCode."}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","value":"YEOFRBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","value":[{"kind":"identifier","text":"YEOFRBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","value":[{"kind":"identifier","text":"YEOFRBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getTrackerData(_:outData:error:)\/title","value":"getTrackerData:outData:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getTrackerData(_:outData:error:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getTrackerData:outData:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}