{"variants":[{"paths":["\/documentation\/yeofr\/yeofrbridge\/learncurrentface(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/yeofrbridge\/learncurrentface(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/learnCurrentFace(_:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Learn\/improve the current face template (optional helper)."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"learnCurrentFace","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tracker","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tracker handle ("},{"type":"codeVoice","code":"HTracker"},{"type":"text","text":" as "},{"type":"codeVoice","code":"int64_t"},{"type":"text","text":")."}]}],"name":"tracker"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Populated on failure with an NSError describing the SDK error."}]}],"name":"error"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"FRBridgeReturnCode"}]}]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"learnCurrentFace","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"learnCurrentFace:error:","kind":"identifier"}],"modules":[{"name":"YEOFR"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol","title":"learnCurrentFace(_:error:)","externalID":"c:objc(cs)YEOFRBridge(cm)learnCurrentFace:error:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"title":"FRBridgeReturnCode","role":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"abstract":[],"title":"YEOFRBridge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"url":"\/documentation\/yeofr\/yeofrbridge","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/learnCurrentFace(_:error:)":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/learnCurrentFace(_:error:)","role":"symbol","url":"\/documentation\/yeofr\/yeofrbridge\/learncurrentface(_:error:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"learnCurrentFace:error:","kind":"identifier"}],"title":"learnCurrentFace(_:error:)","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"learnCurrentFace","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier"}],"abstract":[{"text":"Learn\/improve the current face template (optional helper).","type":"text"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","type":"topic","title":"YEOFR","role":"collection","url":"\/documentation\/yeofr","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"learnCurrentFace:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"learnCurrentFace:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode"},{"kind":"text","text":") "},{"kind":"identifier","text":"learnCurrentFace:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t","text":"int64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tracker"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" **) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Tracker handle (","type":"text"},{"code":"HTracker","type":"codeVoice"},{"text":" as ","type":"text"},{"code":"int64_t","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}],"name":"tracker"},{"content":[{"inlineContent":[{"text":"Populated on failure with an NSError describing the SDK error.","type":"text"}],"type":"paragraph"}],"name":"error"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"FRBridgeReturnCode"}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","value":"YEOFRBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","value":[{"kind":"identifier","text":"YEOFRBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","value":[{"kind":"identifier","text":"YEOFRBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1learnCurrentFace(_:error:)\/title","value":"learnCurrentFace:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1learnCurrentFace(_:error:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"learnCurrentFace:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}