{"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"matchPNGImage:againstBank:matchThreshold:outMatched:outBestSimilarity:error:"}],"title":"matchPNGImage(_:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)","externalID":"c:objc(cs)YEOFRBridge(cm)matchPNGImage:againstBank:matchThreshold:outMatched:outBestSimilarity:error:","modules":[{"name":"YEOFR"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"matchPNGImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"againstBank","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"matchThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outMatched"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","text":"ObjCBool","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"outBestSimilarity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"}],"roleHeading":"Type Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/matchpngimage(_:againstbank:matchthreshold:outmatched:outbestsimilarity:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/matchpngimage(_:againstbank:matchthreshold:outmatched:outbestsimilarity:error:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/matchPNGImage(_:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchPNGImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pngData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"againstBank"},{"text":" ","kind":"text"},{"text":"bank","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"matchThreshold"},{"kind":"text","text":" "},{"kind":"internalParam","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outMatched"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ObjCBool","preciseIdentifier":"s:10ObjectiveC8ObjCBoolV"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"outBestSimilarity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"text":"FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Loads the PNG (FSDK_LoadImageFromPngBuffer → mirror), feeds it to a"},{"type":"text","text":" "},{"type":"text","text":"TEMPORARY tracker — the caller’s live video tracker is never touched, so"},{"type":"text","text":" "},{"type":"text","text":"its tracking\/ID continuity can’t be perturbed by a still — requires"},{"type":"text","text":" "},{"type":"text","text":"exactly one detected face, extracts its FSDK_FaceTemplate, and matches it"},{"type":"text","text":" "},{"type":"text","text":"against every template in "},{"type":"codeVoice","code":"bank"},{"type":"text","text":" (k × sizeof(FSDK_FaceTemplate) bytes,"},{"type":"text","text":" "},{"type":"text","text":"concatenated). "},{"type":"codeVoice","code":"outMatched"},{"type":"text","text":" is YES iff the best FSDK_MatchFaces score"},{"type":"text","text":" "},{"type":"text","text":"clears "},{"type":"codeVoice","code":"threshold"},{"type":"text","text":". ≠ 1 detected face is a negative result (returns OK"},{"type":"text","text":" "},{"type":"text","text":"with outMatched = NO), not an error. Replaces the former count-only"},{"type":"text","text":" "},{"type":"text","text":"checkPNGImageMatchesTracker, which passed any single-face photo."}],"type":"paragraph"}]}],"abstract":[{"text":"Real still-image identity match against a reference bank.","type":"text"}],"sections":[],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","title":"FRBridgeReturnCode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/matchPNGImage(_:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)":{"role":"symbol","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"matchPNGImage:againstBank:matchThreshold:outMatched:outBestSimilarity:error:","kind":"identifier"}],"title":"matchPNGImage(_:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchPNGImage","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"againstBank","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"matchThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outMatched","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","text":"ObjCBool","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"outBestSimilarity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/matchPNGImage(_:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)","kind":"symbol","type":"topic","url":"\/documentation\/yeofr\/yeofrbridge\/matchpngimage(_:againstbank:matchthreshold:outmatched:outbestsimilarity:error:)","abstract":[{"type":"text","text":"Real still-image identity match against a reference bank."}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol","title":"YEOFR","url":"\/documentation\/yeofr","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"role":"collection","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"YEOFRBridge"}],"title":"YEOFRBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOFRBridge"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","kind":"symbol","type":"topic","url":"\/documentation\/yeofr\/yeofrbridge","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"matchPNGImage:againstBank:matchThreshold:outMatched:outBestSimilarity:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"matchPNGImage:againstBank:matchThreshold:outMatched:outBestSimilarity:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"+ (","kind":"text"},{"text":"FRBridgeReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode"},{"text":") ","kind":"text"},{"text":"matchPNGImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"pngData","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"againstBank:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"bank","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"matchThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"text":"threshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outMatched:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" *) ","kind":"text"},{"text":"outMatched","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outBestSimilarity:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" *) ","kind":"text"},{"text":"outBestSimilarity","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" **) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1matchPNGImage(_:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)\/title","value":"matchPNGImage:againstBank:matchThreshold:outMatched:outBestSimilarity:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1matchPNGImage(_:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"matchPNGImage:againstBank:matchThreshold:outMatched:outBestSimilarity:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","value":"YEOFRBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","value":[{"text":"YEOFRBridge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","value":[{"text":"YEOFRBridge","kind":"identifier"}]}]}]}