{"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchingThreshold","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atFAR","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"far","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/matchingthreshold(atfar:outthreshold:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/matchingthreshold(atfar:outthreshold:error:)"]}],"abstract":[{"type":"text","text":"The vendor’s similarity↔FAR calibration (FSDK_GetMatchingThresholdAtFAR):"},{"type":"text","text":" "},{"type":"text","text":"the FSDK_MatchFaces similarity threshold at which the false-acceptance"},{"type":"text","text":" "},{"type":"text","text":"rate equals "},{"code":"far","type":"codeVoice"},{"type":"text","text":". The mapping is owned by the vendor and can change"},{"type":"text","text":" "},{"type":"text","text":"between SDK builds — query it instead of hardcoding similarities."}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchingThreshold","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atFAR","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"}],"externalID":"c:objc(cs)YEOFRBridge(cm)matchingThresholdAtFAR:outThreshold:error:","title":"matchingThreshold(atFAR:outThreshold:error:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"matchingThresholdAtFAR:outThreshold:error:","kind":"identifier"}],"modules":[{"name":"YEOFR"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/matchingThreshold(atFAR:outThreshold:error:)","interfaceLanguage":"swift"},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"title":"YEOFR","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"type":"topic","url":"\/documentation\/yeofr"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"type":"topic","abstract":[],"title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/YEOFRBridge":{"type":"topic","navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge","abstract":[],"role":"symbol","url":"\/documentation\/yeofr\/yeofrbridge","title":"YEOFRBridge"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/YEOFRBridge/matchingThreshold(atFAR:outThreshold:error:)":{"type":"topic","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"matchingThresholdAtFAR:outThreshold:error:"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchingThreshold"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atFAR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"}],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/matchingThreshold(atFAR:outThreshold:error:)","abstract":[{"text":"The vendor’s similarity↔FAR calibration (FSDK_GetMatchingThresholdAtFAR):","type":"text"},{"text":" ","type":"text"},{"text":"the FSDK_MatchFaces similarity threshold at which the false-acceptance","type":"text"},{"text":" ","type":"text"},{"text":"rate equals ","type":"text"},{"code":"far","type":"codeVoice"},{"text":". The mapping is owned by the vendor and can change","type":"text"},{"text":" ","type":"text"},{"text":"between SDK builds — query it instead of hardcoding similarities.","type":"text"}],"role":"symbol","url":"\/documentation\/yeofr\/yeofrbridge\/matchingthreshold(atfar:outthreshold:error:)","title":"matchingThreshold(atFAR:outThreshold:error:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"matchingThresholdAtFAR:outThreshold:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"matchingThresholdAtFAR:outThreshold:error:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","text":"FRBridgeReturnCode"},{"kind":"text","text":") "},{"kind":"identifier","text":"matchingThresholdAtFAR:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"far"},{"kind":"text","text":" "},{"kind":"identifier","text":"outThreshold:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" **) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","op":"replace","value":"FRBridgeReturnCode"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","op":"replace","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","op":"replace","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","op":"replace","value":"YEOFRBridge"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","op":"replace","value":[{"text":"YEOFRBridge","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","op":"replace","value":[{"text":"YEOFRBridge","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1matchingThreshold(atFAR:outThreshold:error:)\/title","op":"replace","value":"matchingThresholdAtFAR:outThreshold:error:"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1matchingThreshold(atFAR:outThreshold:error:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"matchingThresholdAtFAR:outThreshold:error:","kind":"identifier"}]}]}]}