{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/yeofr\/yeofrbridge\/matchimagebuffer(_:width:height:scanline:legacybgra:againstbank:matchthreshold:outmatched:outbestsimilarity:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/yeofrbridge\/matchimagebuffer(_:width:height:scanline:legacybgra:againstbank:matchthreshold:outmatched:outbestsimilarity:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/matchImageBuffer(_:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)"},"metadata":{"externalID":"c:objc(cs)YEOFRBridge(cm)matchImageBuffer:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchImageBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SV","text":"UnsafeRawPointer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scanLine","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"legacyBGRA","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"againstBank","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"matchThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outMatched","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","text":"ObjCBool","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"outBestSimilarity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"}],"symbolKind":"method","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"matchImageBuffer:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:"}],"role":"symbol","roleHeading":"Type Method","modules":[{"name":"YEOFR"}],"title":"matchImageBuffer(_:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)"},"abstract":[{"text":"Real still-image identity match against a reference bank.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchImageBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"buffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SV","text":"UnsafeRawPointer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scanLine","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"legacyBGRA","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"againstBank"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bank"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"matchThreshold"},{"kind":"text","text":" "},{"kind":"internalParam","text":"threshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outMatched"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","kind":"typeIdentifier","text":"ObjCBool"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"outBestSimilarity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","text":"FRBridgeReturnCode"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Takes an 8-bit ","type":"text"},{"inlineContent":[{"type":"text","text":"B, G, R, X"}],"type":"strong"},{"text":" pixel buffer (","type":"text"},{"code":"buffer","type":"codeVoice"},{"text":", ","type":"text"},{"code":"width","type":"codeVoice"},{"text":" × ","type":"text"},{"code":"height","type":"codeVoice"},{"text":",","type":"text"},{"text":" ","type":"text"},{"code":"scanLine","type":"codeVoice"},{"text":" bytes per row) — the same byte order as a camera","type":"text"},{"text":" ","type":"text"},{"code":"kCVPixelFormatType_32BGRA","type":"codeVoice"},{"text":" frame — and loads it with","type":"text"},{"text":" ","type":"text"},{"code":"FSDK_LoadImageFromBuffer","type":"codeVoice"},{"text":" via the shared BGRA→RGBA permute (","type":"text"},{"code":"legacyBGRA","type":"codeVoice"},{"text":" ","type":"text"},{"text":"= NO permutes for an RGBA\/v3 gallery; YES feeds verbatim for a legacy\/v2","type":"text"},{"text":" ","type":"text"},{"text":"gallery, mirroring the live path). The probe is mirrored to share the","type":"text"},{"text":" ","type":"text"},{"text":"front-camera reference space, detected with Luxand’s still-image API","type":"text"},{"text":" ","type":"text"},{"text":"(","type":"text"},{"code":"FSDK_DetectMultipleFaces","type":"codeVoice"},{"text":"\/","type":"text"},{"code":"FSDK_DetectFace","type":"codeVoice"},{"type":"text","text":"), its "},{"code":"FSDK_FaceTemplate","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"extracted, and graded against every template in "},{"type":"codeVoice","code":"bank"},{"type":"text","text":" "},{"type":"text","text":"(k × sizeof(FSDK_FaceTemplate) bytes, concatenated). "},{"type":"codeVoice","code":"outMatched"},{"type":"text","text":" is YES"},{"type":"text","text":" "},{"type":"text","text":"iff the best "},{"type":"codeVoice","code":"FSDK_MatchFaces"},{"type":"text","text":" score clears "},{"code":"threshold","type":"codeVoice"},{"type":"text","text":". No detectable"},{"type":"text","text":" "},{"type":"text","text":"face is a negative result (returns OK with outMatched = NO \/ best 0), not"},{"type":"text","text":" "},{"type":"text","text":"an error."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Replaces the former PNG-buffer entry point: iPhone library photos are"},{"type":"text","text":" "},{"type":"text","text":"often Display-P3\/16-bit, which the FaceSDK’s libpng path mis-decoded; the"},{"type":"text","text":" "},{"type":"text","text":"caller now renders a deterministic sRGB 8-bit buffer (see"},{"type":"text","text":" "},{"type":"codeVoice","code":"UIImage.normalizedBGRA8888"},{"type":"text","text":")."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/YEOFRBridge":{"type":"topic","navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge","abstract":[],"role":"symbol","url":"\/documentation\/yeofr\/yeofrbridge","title":"YEOFRBridge"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"type":"topic","abstract":[],"title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"title":"YEOFR","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"type":"topic","url":"\/documentation\/yeofr"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/YEOFRBridge/matchImageBuffer(_:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchImageBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SV","text":"UnsafeRawPointer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"legacyBGRA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"againstBank"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"matchThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outMatched"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","text":"ObjCBool"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"outBestSimilarity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode"}],"abstract":[{"text":"Real still-image identity match against a reference bank.","type":"text"}],"title":"matchImageBuffer(_:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)","url":"\/documentation\/yeofr\/yeofrbridge\/matchimagebuffer(_:width:height:scanline:legacybgra:againstbank:matchthreshold:outmatched:outbestsimilarity:error:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"matchImageBuffer:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:"}],"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/matchImageBuffer(_:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"matchImageBuffer:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"matchImageBuffer:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"+ (","kind":"text"},{"text":"FRBridgeReturnCode","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode"},{"text":") ","kind":"text"},{"text":"matchImageBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" *) ","kind":"text"},{"text":"buffer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"width:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int32_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int32_t"},{"text":") ","kind":"text"},{"text":"width","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"height:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int32_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int32_t"},{"text":") ","kind":"text"},{"text":"height","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"scanLine:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int32_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int32_t"},{"text":") ","kind":"text"},{"text":"scanLine","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"legacyBGRA:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"legacyBGRA","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"againstBank:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"bank","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"matchThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"text":"threshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outMatched:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" *) ","kind":"text"},{"text":"outMatched","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outBestSimilarity:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" *) ","kind":"text"},{"text":"outBestSimilarity","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" **) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"YEOFRBridge","op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title"},{"value":[{"kind":"identifier","text":"YEOFRBridge"}],"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments"},{"value":[{"kind":"identifier","text":"YEOFRBridge"}],"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle"},{"value":"FRBridgeReturnCode","op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle"},{"value":"matchImageBuffer:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:","op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1matchImageBuffer(_:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"matchImageBuffer:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1matchImageBuffer(_:width:height:scanLine:legacyBGRA:againstBank:matchThreshold:outMatched:outBestSimilarity:error:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}