{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:legacybgra:outids:outnames:outrects:referencetemplate:outsimilarities:outdetectedcount:error:)"]},{"paths":["\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:legacybgra:outids:outnames:outrects:referencetemplate:outsimilarities:outdetectedcount:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)"},"abstract":[{"type":"text","text":"Process a single BGRA32 frame through the SDK pipeline."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBuffer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeRawPointer","preciseIdentifier":"s:SV"},{"kind":"text","text":", "},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanLine"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tracker","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needFaceRect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ratio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"legacyBGRA"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"outIDs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outNames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":"?>?, ","kind":"text"},{"kind":"externalParam","text":"outRects"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":"?>?, ","kind":"text"},{"kind":"externalParam","text":"referenceTemplate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"outSimilarities"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":"?>?, "},{"text":"outDetectedCount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":">?, ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"}]}],"kind":"declarations"},{"parameters":[{"name":"buffer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Pointer to BGRA32 pixel data (kCVPixelFormatType_32BGRA, as iOS"},{"text":" ","type":"text"},{"type":"text","text":"AVFoundation delivers it; the bridge permutes B<->R before loading)."}]}]},{"name":"width","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame width in pixels."}]}]},{"name":"height","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame height in pixels."}]}]},{"name":"scanLine","content":[{"inlineContent":[{"type":"text","text":"Bytes per row (stride)."}],"type":"paragraph"}]},{"name":"tracker","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tracker handle ("},{"code":"HTracker","type":"codeVoice"},{"type":"text","text":") as "},{"code":"int64_t","type":"codeVoice"},{"type":"text","text":"."}]}]},{"name":"needFaceRect","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If YES, computes face rects (additional per-face call)."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Scale factor to apply to rects (mirrors your Swift "},{"code":"imageFrameParameters.ratio","type":"codeVoice"},{"type":"text","text":")."}]}],"name":"ratio"},{"name":"legacyBGRA","content":[{"inlineContent":[{"type":"text","text":"NO (default) permutes the BGRA buffer to the R,G,B,A order Luxand expects. YES"},{"type":"text","text":" "},{"type":"text","text":"feeds it verbatim — only for galleries enrolled before the colour-order fix, whose"},{"type":"text","text":" "},{"type":"text","text":"stored templates live in the old swapped colour space (see "},{"code":"TrackerColorOrder","type":"codeVoice"},{"type":"text","text":")."}],"type":"paragraph"}]},{"name":"outIDs","content":[{"inlineContent":[{"type":"text","text":"On success, receives an NSArray<NSNumber*> of face IDs (Int64)."}],"type":"paragraph"}]},{"name":"outNames","content":[{"inlineContent":[{"type":"text","text":"On success, receives an NSDictionary<NSNumber*, NSString*> mapping ID → name (empty string or absence means not enrolled)."}],"type":"paragraph"}]},{"name":"outRects","content":[{"inlineContent":[{"type":"text","text":"On success, receives an NSDictionary<NSNumber*, NSValue(CGRect)> mapping ID → face rect (image coordinates)."}],"type":"paragraph"}]},{"name":"referenceTemplate","content":[{"inlineContent":[{"type":"text","text":"Optional enrolment reference "},{"type":"emphasis","inlineContent":[{"type":"text","text":"bank"}]},{"type":"text","text":": k concatenated "},{"code":"FSDK_FaceTemplate","type":"codeVoice"},{"type":"text","text":" blobs"},{"type":"text","text":" "},{"type":"text","text":"(each from "},{"code":"extractReferenceTemplate…","type":"codeVoice"},{"type":"text","text":"; length must be a whole multiple of"},{"type":"text","text":" "},{"code":"sizeof(FSDK_FaceTemplate)","type":"codeVoice"},{"type":"text","text":"). When supplied, each tracked face’s live template is"},{"type":"text","text":" "},{"type":"text","text":"extracted once and matched against every banked template ("},{"code":"FSDK_MatchFaces","type":"codeVoice"},{"type":"text","text":"); the"},{"type":"text","text":" "},{"type":"strong","inlineContent":[{"type":"text","text":"max"}]},{"type":"text","text":" similarity is reported. A single-template blob (k=1) behaves as before."}],"type":"paragraph"}]},{"name":"outSimilarities","content":[{"inlineContent":[{"type":"text","text":"When "},{"type":"codeVoice","code":"referenceTemplate"},{"type":"text","text":" is supplied, receives an NSDictionary<NSNumber*, NSNumber*>"},{"type":"text","text":" "},{"type":"text","text":"mapping ID → best match similarity (Float in [0,1]). Faces whose template could not be"},{"type":"text","text":" "},{"type":"text","text":"extracted are simply absent. "},{"type":"codeVoice","code":"@{}"},{"type":"text","text":" when no reference template is given."}],"type":"paragraph"}]},{"name":"outDetectedCount","content":[{"inlineContent":[{"text":"On success, receives the number of detected faces.","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"Populated on failure with an NSError describing the SDK error."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"FRBridgeReturnCode."}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Steps performed:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Load image from buffer, permuting BGRA -> RGBA (Luxand’s","type":"text"},{"text":" ","type":"text"},{"text":"FSDK_IMAGE_COLOR_32BIT expects R,G,B,A order)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Mirror image horizontally","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Feed tracker","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Retrieve names per ID","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"(Optional) Estimate face rect from tracker eyes","type":"text"}]}]}]},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"buffer"},{"type":"text","text":" memory is owned by the caller and must remain valid for the call duration."}]}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SV","text":"UnsafeRawPointer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needFaceRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ratio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"legacyBGRA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outIDs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"text":"?>?, ","kind":"text"},{"text":"outNames","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":"?>?, ","kind":"text"},{"text":"outRects","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"referenceTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outSimilarities"},{"kind":"text","text":": "},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":"?>?, ","kind":"text"},{"text":"outDetectedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:","kind":"identifier"}],"modules":[{"name":"YEOFR"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol","title":"processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)","externalID":"c:objc(cs)YEOFRBridge(cm)processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"title":"FRBridgeReturnCode","role":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"abstract":[],"title":"YEOFRBridge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"url":"\/documentation\/yeofr\/yeofrbridge","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","type":"topic","title":"YEOFR","role":"collection","url":"\/documentation\/yeofr","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)":{"title":"processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)","abstract":[{"type":"text","text":"Process a single BGRA32 frame through the SDK pipeline."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"processFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:SV"},{"text":", ","kind":"text"},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"scanLine","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"tracker","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needFaceRect"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ratio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"legacyBGRA","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"outIDs","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"text":"?>?, ","kind":"text"},{"text":"outNames","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":"?>?, ","kind":"text"},{"text":"outRects","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"referenceTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outSimilarities"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outDetectedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:","kind":"identifier"}],"url":"\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:legacybgra:outids:outnames:outrects:referencetemplate:outsimilarities:outdetectedcount:error:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode"},{"kind":"text","text":") "},{"kind":"identifier","text":"processFrameWithBuffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"width:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":") "},{"kind":"internalParam","text":"width"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":") "},{"kind":"internalParam","text":"height"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanLine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scanLine"},{"text":" ","kind":"text"},{"text":"tracker:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t"},{"text":") ","kind":"text"},{"text":"tracker","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"needFaceRect:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"needFaceRect","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ratio:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"text":"ratio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"legacyBGRA:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"legacyBGRA","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outIDs:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" **) ","kind":"text"},{"text":"outIDs","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outNames:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSNumber *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" **) ","kind":"text"},{"text":"outNames","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outRects:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSNumber *,NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" **) ","kind":"text"},{"text":"outRects","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"referenceTemplate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"referenceTemplate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outSimilarities:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSNumber *,NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" **) ","kind":"text"},{"text":"outSimilarities","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outDetectedCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" *) ","kind":"text"},{"text":"outDetectedCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" **) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"buffer","content":[{"type":"paragraph","inlineContent":[{"text":"Pointer to BGRA32 pixel data (kCVPixelFormatType_32BGRA, as iOS","type":"text"},{"text":" ","type":"text"},{"text":"AVFoundation delivers it; the bridge permutes B<->R before loading).","type":"text"}]}]},{"name":"width","content":[{"type":"paragraph","inlineContent":[{"text":"Frame width in pixels.","type":"text"}]}]},{"name":"height","content":[{"type":"paragraph","inlineContent":[{"text":"Frame height in pixels.","type":"text"}]}]},{"name":"scanLine","content":[{"type":"paragraph","inlineContent":[{"text":"Bytes per row (stride).","type":"text"}]}]},{"name":"tracker","content":[{"type":"paragraph","inlineContent":[{"text":"Tracker handle (","type":"text"},{"code":"HTracker","type":"codeVoice"},{"text":") as ","type":"text"},{"code":"int64_t","type":"codeVoice"},{"text":".","type":"text"}]}]},{"name":"needFaceRect","content":[{"type":"paragraph","inlineContent":[{"text":"If YES, computes face rects (additional per-face call).","type":"text"}]}]},{"name":"ratio","content":[{"type":"paragraph","inlineContent":[{"text":"Scale factor to apply to rects (mirrors your Swift ","type":"text"},{"code":"imageFrameParameters.ratio","type":"codeVoice"},{"text":").","type":"text"}]}]},{"name":"legacyBGRA","content":[{"type":"paragraph","inlineContent":[{"text":"NO (default) permutes the BGRA buffer to the R,G,B,A order Luxand expects. YES","type":"text"},{"text":" ","type":"text"},{"text":"feeds it verbatim — only for galleries enrolled before the colour-order fix, whose","type":"text"},{"text":" ","type":"text"},{"text":"stored templates live in the old swapped colour space (see ","type":"text"},{"code":"TrackerColorOrder","type":"codeVoice"},{"text":").","type":"text"}]}]},{"name":"outIDs","content":[{"type":"paragraph","inlineContent":[{"text":"On success, receives an NSArray<NSNumber*> of face IDs (Int64).","type":"text"}]}]},{"name":"outNames","content":[{"type":"paragraph","inlineContent":[{"text":"On success, receives an NSDictionary<NSNumber*, NSString*> mapping ID → name (empty string or absence means not enrolled).","type":"text"}]}]},{"name":"outRects","content":[{"type":"paragraph","inlineContent":[{"text":"On success, receives an NSDictionary<NSNumber*, NSValue(CGRect)> mapping ID → face rect (image coordinates).","type":"text"}]}]},{"name":"referenceTemplate","content":[{"type":"paragraph","inlineContent":[{"text":"Optional enrolment reference ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"bank"}]},{"text":": k concatenated ","type":"text"},{"code":"FSDK_FaceTemplate","type":"codeVoice"},{"text":" blobs","type":"text"},{"text":" ","type":"text"},{"text":"(each from ","type":"text"},{"code":"extractReferenceTemplate…","type":"codeVoice"},{"text":"; length must be a whole multiple of","type":"text"},{"text":" ","type":"text"},{"code":"sizeof(FSDK_FaceTemplate)","type":"codeVoice"},{"text":"). When supplied, each tracked face’s live template is","type":"text"},{"text":" ","type":"text"},{"text":"extracted once and matched against every banked template (","type":"text"},{"code":"FSDK_MatchFaces","type":"codeVoice"},{"text":"); the","type":"text"},{"text":" ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"max"}]},{"text":" similarity is reported. A single-template blob (k=1) behaves as before.","type":"text"}]}]},{"name":"outSimilarities","content":[{"type":"paragraph","inlineContent":[{"text":"When ","type":"text"},{"code":"referenceTemplate","type":"codeVoice"},{"text":" is supplied, receives an NSDictionary<NSNumber*, NSNumber*>","type":"text"},{"text":" ","type":"text"},{"text":"mapping ID → best match similarity (Float in [0,1]). Faces whose template could not be","type":"text"},{"text":" ","type":"text"},{"text":"extracted are simply absent. ","type":"text"},{"code":"@{}","type":"codeVoice"},{"text":" when no reference template is given.","type":"text"}]}]},{"name":"outDetectedCount","content":[{"type":"paragraph","inlineContent":[{"text":"On success, receives the number of detected faces.","type":"text"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"Populated on failure with an NSError describing the SDK error.","type":"text"}]}]}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"FRBridgeReturnCode."}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode","op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","value":"YEOFRBridge","op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","value":[{"kind":"identifier","text":"YEOFRBridge"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","value":[{"kind":"identifier","text":"YEOFRBridge"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)\/title","value":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:legacyBGRA:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:"}],"op":"replace"}]}]}