{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:outids:outnames:outrects:outdetectedcount:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:outids:outnames:outrects:outdetectedcount:error:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBuffer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeRawPointer","preciseIdentifier":"s:SV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needFaceRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ratio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outIDs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outNames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outRects"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outDetectedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"parameters":[{"name":"buffer","content":[{"inlineContent":[{"type":"text","text":"Pointer to ARGB32 pixel data (compatible with FSDK_LoadImageFromBuffer)."}],"type":"paragraph"}]},{"name":"width","content":[{"inlineContent":[{"type":"text","text":"Frame width in pixels."}],"type":"paragraph"}]},{"name":"height","content":[{"inlineContent":[{"type":"text","text":"Frame height in pixels."}],"type":"paragraph"}]},{"name":"scanLine","content":[{"inlineContent":[{"type":"text","text":"Bytes per row (stride)."}],"type":"paragraph"}]},{"name":"tracker","content":[{"inlineContent":[{"type":"text","text":"Tracker handle ("},{"type":"codeVoice","code":"HTracker"},{"type":"text","text":") as "},{"type":"codeVoice","code":"int64_t"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"needFaceRect","content":[{"inlineContent":[{"type":"text","text":"If YES, computes face rects (additional per-face call)."}],"type":"paragraph"}]},{"name":"ratio","content":[{"inlineContent":[{"type":"text","text":"Scale factor to apply to rects (mirrors your Swift "},{"type":"codeVoice","code":"imageFrameParameters.ratio"},{"type":"text","text":")."}],"type":"paragraph"}]},{"name":"outIDs","content":[{"inlineContent":[{"type":"text","text":"On success, receives an NSArray<NSNumber*> of face IDs (Int64)."}],"type":"paragraph"}]},{"name":"outNames","content":[{"inlineContent":[{"type":"text","text":"On success, receives an NSDictionary<NSNumber*, NSString*> mapping ID → name (empty string or absence means not enrolled)."}],"type":"paragraph"}]},{"name":"outRects","content":[{"inlineContent":[{"type":"text","text":"On success, receives an NSDictionary<NSNumber*, NSValue(CGRect)> mapping ID → face rect (image coordinates)."}],"type":"paragraph"}]},{"name":"outDetectedCount","content":[{"inlineContent":[{"type":"text","text":"On success, receives the number of detected faces."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"Populated on failure with an NSError describing the SDK error."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"FRSDKReturnCode."}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Steps performed:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Load image from buffer","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Mirror image horizontally","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Feed tracker","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Retrieve names per ID","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"(Optional) Estimate face rect from tracker eyes","type":"text"}]}]}],"type":"orderedList"},{"name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"buffer"},{"type":"text","text":" memory is owned by the caller and must remain valid for the call duration."}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Process a single ARGB32 frame through the SDK pipeline.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"sections":[],"kind":"symbol","metadata":{"title":"processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SV","text":"UnsafeRawPointer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needFaceRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ratio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outIDs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outNames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outRects"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outDetectedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:","kind":"identifier"}],"modules":[{"name":"YEOFR"}],"externalID":"c:objc(cs)YEOFRBridge(cm)processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:"},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"FRSDKReturnCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","url":"\/documentation\/yeofr\/frsdkreturncode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Process a single ARGB32 frame through the SDK pipeline."}],"type":"topic","title":"processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"processFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:SV"},{"text":", ","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"scanLine","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracker"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needFaceRect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ratio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outIDs"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outNames"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outRects"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outDetectedCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier","text":"FRSDKReturnCode"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)","url":"\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:outids:outnames:outrects:outdetectedcount:error:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"url":"\/documentation\/yeofr\/yeofrbridge","navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"YEOFRBridge"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","kind":"symbol","title":"YEOFRBridge","abstract":[],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"type":"topic","title":"YEOFR","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","text":"FRSDKReturnCode"},{"kind":"text","text":") "},{"kind":"identifier","text":"processFrameWithBuffer:"},{"kind":"text","text":"("},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"width:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"internalParam","text":"width"},{"text":" ","kind":"text"},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"text":"int","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"text":") ","kind":"text"},{"text":"height","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"scanLine:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"text":") ","kind":"text"},{"text":"scanLine","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracker:"},{"text":"(","kind":"text"},{"text":"int64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tracker"},{"kind":"text","text":" "},{"kind":"identifier","text":"needFaceRect:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"needFaceRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"ratio:"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"ratio"},{"kind":"text","text":" "},{"kind":"identifier","text":"outIDs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" **) "},{"kind":"internalParam","text":"outIDs"},{"kind":"text","text":" "},{"kind":"identifier","text":"outNames:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSNumber *,NSString *>","kind":"typeIdentifier"},{"text":" **) ","kind":"text"},{"text":"outNames","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outRects:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSNumber *,NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" **) ","kind":"text"},{"text":"outRects","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outDetectedCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outDetectedCount"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" **) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"buffer","content":[{"inlineContent":[{"text":"Pointer to ARGB32 pixel data (compatible with FSDK_LoadImageFromBuffer).","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Frame width in pixels."}],"type":"paragraph"}],"name":"width"},{"content":[{"inlineContent":[{"text":"Frame height in pixels.","type":"text"}],"type":"paragraph"}],"name":"height"},{"content":[{"inlineContent":[{"text":"Bytes per row (stride).","type":"text"}],"type":"paragraph"}],"name":"scanLine"},{"name":"tracker","content":[{"inlineContent":[{"text":"Tracker handle (","type":"text"},{"code":"HTracker","type":"codeVoice"},{"type":"text","text":") as "},{"code":"int64_t","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"needFaceRect","content":[{"inlineContent":[{"type":"text","text":"If YES, computes face rects (additional per-face call)."}],"type":"paragraph"}]},{"name":"ratio","content":[{"inlineContent":[{"text":"Scale factor to apply to rects (mirrors your Swift ","type":"text"},{"code":"imageFrameParameters.ratio","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}]},{"name":"outIDs","content":[{"inlineContent":[{"text":"On success, receives an NSArray<NSNumber*> of face IDs (Int64).","type":"text"}],"type":"paragraph"}]},{"name":"outNames","content":[{"inlineContent":[{"text":"On success, receives an NSDictionary<NSNumber*, NSString*> mapping ID → name (empty string or absence means not enrolled).","type":"text"}],"type":"paragraph"}]},{"name":"outRects","content":[{"inlineContent":[{"text":"On success, receives an NSDictionary<NSNumber*, NSValue(CGRect)> mapping ID → face rect (image coordinates).","type":"text"}],"type":"paragraph"}]},{"name":"outDetectedCount","content":[{"inlineContent":[{"text":"On success, receives the number of detected faces.","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"Populated on failure with an NSError describing the SDK error.","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"FRSDKReturnCode.","type":"text"}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","value":"FRSDKReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)\/title","value":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","value":"YEOFRBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","value":[{"kind":"identifier","text":"YEOFRBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","value":[{"kind":"identifier","text":"YEOFRBridge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}