{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)"},"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"metadata":{"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeRawPointer","preciseIdentifier":"s:SV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scanLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"tracker","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needFaceRect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ratio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outIDs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"text":"?>?, ","kind":"text"},{"text":"outNames","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outRects"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"referenceTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"text":"outSimilarities","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?>?, "},{"text":"outDetectedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier"}],"modules":[{"name":"YEOFR"}],"role":"symbol","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:","kind":"identifier"}],"title":"processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)","symbolKind":"method","externalID":"c:objc(cs)YEOFRBridge(cm)processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:"},"abstract":[{"text":"Process a single ARGB32 frame through the SDK pipeline.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBuffer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SV","text":"UnsafeRawPointer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"scanLine","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tracker"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needFaceRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"ratio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outIDs"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outNames"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outRects"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":"?>?, ","kind":"text"},{"text":"referenceTemplate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"outSimilarities","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":"?>?, ","kind":"text"},{"text":"outDetectedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"}]}],"kind":"declarations"},{"parameters":[{"name":"buffer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Pointer to ARGB32 pixel data (compatible with FSDK_LoadImageFromBuffer)."}]}]},{"name":"width","content":[{"type":"paragraph","inlineContent":[{"text":"Frame width in pixels.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Frame height in pixels.","type":"text"}],"type":"paragraph"}],"name":"height"},{"content":[{"inlineContent":[{"type":"text","text":"Bytes per row (stride)."}],"type":"paragraph"}],"name":"scanLine"},{"name":"tracker","content":[{"type":"paragraph","inlineContent":[{"text":"Tracker handle (","type":"text"},{"type":"codeVoice","code":"HTracker"},{"text":") as ","type":"text"},{"type":"codeVoice","code":"int64_t"},{"type":"text","text":"."}]}]},{"name":"needFaceRect","content":[{"type":"paragraph","inlineContent":[{"text":"If YES, computes face rects (additional per-face call).","type":"text"}]}]},{"name":"ratio","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Scale factor to apply to rects (mirrors your Swift "},{"type":"codeVoice","code":"imageFrameParameters.ratio"},{"type":"text","text":")."}]}]},{"name":"outIDs","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On success, receives an NSArray<NSNumber*> of face IDs (Int64)."}]}]},{"name":"outNames","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On success, receives an NSDictionary<NSNumber*, NSString*> mapping ID → name (empty string or absence means not enrolled)."}]}]},{"name":"outRects","content":[{"type":"paragraph","inlineContent":[{"text":"On success, receives an NSDictionary<NSNumber*, NSValue(CGRect)> mapping ID → face rect (image coordinates).","type":"text"}]}]},{"name":"referenceTemplate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional enrolment reference "},{"type":"emphasis","inlineContent":[{"text":"bank","type":"text"}]},{"type":"text","text":": k concatenated "},{"code":"FSDK_FaceTemplate","type":"codeVoice"},{"text":" blobs","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(each from "},{"type":"codeVoice","code":"extractReferenceTemplate…"},{"text":"; length must be a whole multiple of","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"sizeof(FSDK_FaceTemplate)"},{"type":"text","text":"). When supplied, each tracked face’s live template is"},{"type":"text","text":" "},{"type":"text","text":"extracted once and matched against every banked template ("},{"type":"codeVoice","code":"FSDK_MatchFaces"},{"type":"text","text":"); the"},{"text":" ","type":"text"},{"type":"strong","inlineContent":[{"text":"max","type":"text"}]},{"text":" similarity is reported. A single-template blob (k=1) behaves as before.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When "},{"type":"codeVoice","code":"referenceTemplate"},{"type":"text","text":" is supplied, receives an NSDictionary<NSNumber*, NSNumber*>"},{"type":"text","text":" "},{"type":"text","text":"mapping ID → best match similarity (Float in [0,1]). Faces whose template could not be"},{"text":" ","type":"text"},{"text":"extracted are simply absent. ","type":"text"},{"code":"@{}","type":"codeVoice"},{"text":" when no reference template is given.","type":"text"}]}],"name":"outSimilarities"},{"content":[{"inlineContent":[{"type":"text","text":"On success, receives the number of detected faces."}],"type":"paragraph"}],"name":"outDetectedCount"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Populated on failure with an NSError describing the SDK error.","type":"text"}]}],"name":"error"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"text":"FRBridgeReturnCode.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Steps performed:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Load image from buffer","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Mirror image horizontally"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Feed tracker","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Retrieve names per ID"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) Estimate face rect from tracker eyes"}]}]}],"type":"orderedList"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"buffer"},{"text":" memory is owned by the caller and must remain valid for the call duration.","type":"text"}]}],"type":"aside","style":"note"}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:outids:outnames:outrects:referencetemplate:outsimilarities:outdetectedcount:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:outids:outnames:outrects:referencetemplate:outsimilarities:outdetectedcount:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/YEOFRBridge":{"abstract":[],"kind":"symbol","url":"\/documentation\/yeofr\/yeofrbridge","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge","title":"YEOFRBridge","navigatorTitle":[{"kind":"identifier","text":"YEOFRBridge"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"YEOFRBridge","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"title":"FRBridgeReturnCode","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/YEOFRBridge/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)":{"title":"processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)","type":"topic","url":"\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:outids:outnames:outrects:referencetemplate:outsimilarities:outdetectedcount:error:)","abstract":[{"type":"text","text":"Process a single ARGB32 frame through the SDK pipeline."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeRawPointer","preciseIdentifier":"s:SV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scanLine","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tracker","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"needFaceRect","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ratio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outIDs"},{"kind":"text","text":": "},{"text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"text":"?>?, ","kind":"text"},{"text":"outNames","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":"?>?, ","kind":"text"},{"text":"outRects","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":"?>?, ","kind":"text"},{"text":"referenceTemplate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"outSimilarities","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":"?>?, ","kind":"text"},{"text":"outDetectedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:"}],"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"role":"collection","type":"topic","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","title":"YEOFR","url":"\/documentation\/yeofr","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"processFrameWithBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"buffer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"width:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"width","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"height:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"height","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"scanLine:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int","preciseIdentifier":"c:I","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scanLine","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracker:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t","text":"int64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tracker"},{"kind":"text","text":" "},{"kind":"identifier","text":"needFaceRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"needFaceRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"ratio:"},{"kind":"text","text":"("},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"text":"ratio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outIDs:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" **) ","kind":"text"},{"text":"outIDs","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outNames:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSNumber *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" **) ","kind":"text"},{"text":"outNames","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outRects:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSNumber *,NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" **) ","kind":"text"},{"text":"outRects","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"referenceTemplate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"referenceTemplate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outSimilarities:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSNumber *,NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" **) ","kind":"text"},{"text":"outSimilarities","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outDetectedCount:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" *) "},{"text":"outDetectedCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" **) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Pointer to ARGB32 pixel data (compatible with FSDK_LoadImageFromBuffer).","type":"text"}]}],"name":"buffer"},{"content":[{"inlineContent":[{"type":"text","text":"Frame width in pixels."}],"type":"paragraph"}],"name":"width"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Frame height in pixels.","type":"text"}]}],"name":"height"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Bytes per row (stride)."}]}],"name":"scanLine"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Tracker handle (","type":"text"},{"code":"HTracker","type":"codeVoice"},{"text":") as ","type":"text"},{"code":"int64_t","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"tracker"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If YES, computes face rects (additional per-face call).","type":"text"}]}],"name":"needFaceRect"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Scale factor to apply to rects (mirrors your Swift ","type":"text"},{"code":"imageFrameParameters.ratio","type":"codeVoice"},{"text":").","type":"text"}]}],"name":"ratio"},{"content":[{"inlineContent":[{"text":"On success, receives an NSArray<NSNumber*> of face IDs (Int64).","type":"text"}],"type":"paragraph"}],"name":"outIDs"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On success, receives an NSDictionary<NSNumber*, NSString*> mapping ID → name (empty string or absence means not enrolled)."}]}],"name":"outNames"},{"content":[{"inlineContent":[{"type":"text","text":"On success, receives an NSDictionary<NSNumber*, NSValue(CGRect)> mapping ID → face rect (image coordinates)."}],"type":"paragraph"}],"name":"outRects"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional enrolment reference "},{"type":"emphasis","inlineContent":[{"type":"text","text":"bank"}]},{"type":"text","text":": k concatenated "},{"code":"FSDK_FaceTemplate","type":"codeVoice"},{"type":"text","text":" blobs"},{"type":"text","text":" "},{"type":"text","text":"(each from "},{"code":"extractReferenceTemplate…","type":"codeVoice"},{"type":"text","text":"; length must be a whole multiple of"},{"type":"text","text":" "},{"code":"sizeof(FSDK_FaceTemplate)","type":"codeVoice"},{"type":"text","text":"). When supplied, each tracked face’s live template is"},{"type":"text","text":" "},{"type":"text","text":"extracted once and matched against every banked template ("},{"code":"FSDK_MatchFaces","type":"codeVoice"},{"type":"text","text":"); the"},{"type":"text","text":" "},{"type":"strong","inlineContent":[{"type":"text","text":"max"}]},{"type":"text","text":" similarity is reported. A single-template blob (k=1) behaves as before."}]}],"name":"referenceTemplate"},{"content":[{"inlineContent":[{"type":"text","text":"When "},{"type":"codeVoice","code":"referenceTemplate"},{"type":"text","text":" is supplied, receives an NSDictionary<NSNumber*, NSNumber*>"},{"type":"text","text":" "},{"text":"mapping ID → best match similarity (Float in [0,1]). Faces whose template could not be","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"extracted are simply absent. "},{"type":"codeVoice","code":"@{}"},{"type":"text","text":" when no reference template is given."}],"type":"paragraph"}],"name":"outSimilarities"},{"content":[{"type":"paragraph","inlineContent":[{"text":"On success, receives the number of detected faces.","type":"text"}]}],"name":"outDetectedCount"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Populated on failure with an NSError describing the SDK error."}]}],"name":"error"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"FRBridgeReturnCode.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","op":"replace","value":"YEOFRBridge"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","op":"replace","value":[{"kind":"identifier","text":"YEOFRBridge"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","op":"replace","value":[{"text":"YEOFRBridge","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","op":"replace","value":"FRBridgeReturnCode"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","op":"replace","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)\/title","op":"replace","value":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:referenceTemplate:outSimilarities:outDetectedCount:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}