{"sections":[],"variants":[{"paths":["\/documentation\/yeofr\/yeofrbridge\/settrackerparameters(_:paramsutf8:outerrorposition:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/yeofrbridge\/settrackerparameters(_:paramsutf8:outerrorposition:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Apply tracker parameters from an FRSDK-formatted parameter string."}],"metadata":{"modules":[{"name":"YEOFR"}],"externalID":"c:objc(cs)YEOFRBridge(cm)setTrackerParameters:paramsUTF8:outErrorPosition:error:","role":"symbol","title":"setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"setTrackerParameters:paramsUTF8:outErrorPosition:error:","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTrackerParameters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"paramsUTF8","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"outErrorPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier"}],"roleHeading":"Type Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTrackerParameters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tracker","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"text":"paramsUTF8","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"params","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outErrorPosition"},{"kind":"text","text":" "},{"kind":"internalParam","text":"outErrPos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Tracker handle (","type":"text"},{"code":"HTracker","type":"codeVoice"},{"text":" as ","type":"text"},{"code":"int64_t","type":"codeVoice"},{"text":").","type":"text"}]}],"name":"tracker"},{"content":[{"inlineContent":[{"type":"text","text":"Parameter string (same format as "},{"code":"config.asTrackerParameters","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}],"name":"params"},{"name":"outErrPos","content":[{"type":"paragraph","inlineContent":[{"text":"Receives the 1-based position of the first error in the string; 0 on success.","type":"text"}]}]},{"name":"error","content":[{"inlineContent":[{"text":"If ","type":"text"},{"code":"outErrPos != 0","type":"codeVoice"},{"type":"text","text":", also populated with a descriptive NSError."}],"type":"paragraph"}]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"FRBridgeReturnCode.","type":"text"}]}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Wraps "},{"type":"codeVoice","code":"FSDK_SetTrackerMultipleParameters"},{"type":"text","text":". Useful to atomically set multiple"},{"type":"text","text":" "},{"type":"text","text":"parameters; check "},{"type":"codeVoice","code":"outErrPos"},{"type":"text","text":" for the failing position if NO is returned."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"kind":"symbol","references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"type":"topic","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode","title":"FRBridgeReturnCode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRBridgeReturnCode"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)":{"url":"\/documentation\/yeofr\/yeofrbridge\/settrackerparameters(_:paramsutf8:outerrorposition:error:)","type":"topic","title":"setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTrackerParameters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"paramsUTF8","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"outErrorPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":">?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"text":") -> ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode"}],"abstract":[{"type":"text","text":"Apply tracker parameters from an FRSDK-formatted parameter string."}],"kind":"symbol","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"setTrackerParameters:paramsUTF8:outErrorPosition:error:","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"title":"YEOFRBridge","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"type":"topic","url":"\/documentation\/yeofr\/yeofrbridge","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"abstract":[]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"type":"topic","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"title":"YEOFR","url":"\/documentation\/yeofr","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setTrackerParameters:paramsUTF8:outErrorPosition:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setTrackerParameters:paramsUTF8:outErrorPosition:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRBridgeReturnCode","text":"FRBridgeReturnCode"},{"kind":"text","text":") "},{"kind":"identifier","text":"setTrackerParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t","text":"int64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tracker"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramsUTF8:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"params"},{"kind":"text","text":" "},{"kind":"identifier","text":"outErrorPosition:"},{"kind":"text","text":"("},{"text":"int32_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int32_t"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outErrPos"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" **) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tracker handle ("},{"type":"codeVoice","code":"HTracker"},{"type":"text","text":" as "},{"type":"codeVoice","code":"int64_t"},{"type":"text","text":")."}]}],"name":"tracker"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter string (same format as "},{"code":"config.asTrackerParameters","type":"codeVoice"},{"type":"text","text":")."}]}],"name":"params"},{"name":"outErrPos","content":[{"inlineContent":[{"type":"text","text":"Receives the 1-based position of the first error in the string; 0 on success."}],"type":"paragraph"}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"outErrPos != 0"},{"type":"text","text":", also populated with a descriptive NSError."}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"FRBridgeReturnCode.","type":"text"}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","op":"replace","value":"FRBridgeReturnCode"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","op":"replace","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)\/title","op":"replace","value":"setTrackerParameters:paramsUTF8:outErrorPosition:error:"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setTrackerParameters:paramsUTF8:outErrorPosition:error:"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","op":"replace","value":"YEOFRBridge"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","op":"replace","value":[{"kind":"identifier","text":"YEOFRBridge"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","op":"replace","value":[{"text":"YEOFRBridge","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}