{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rc"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier","text":"FRBridgeReturnCode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"string(for:)","symbolKind":"method","modules":[{"name":"YEOFR"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"stringForReturnCode:","kind":"identifier"}],"externalID":"c:objc(cs)YEOFRBridge(cm)stringForReturnCode:"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/yeofr\/yeofrbridge\/string(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/yeofrbridge\/string(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/string(for:)"},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/YEOFRBridge/string(for:)":{"title":"string(for:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/yeofr\/yeofrbridge\/string(for:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringForReturnCode:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/string(for:)"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"role":"symbol","title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol","type":"topic","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","url":"\/documentation\/yeofr","kind":"symbol","type":"topic","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"title":"YEOFR","role":"collection"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/YEOFRBridge":{"role":"symbol","title":"YEOFRBridge","navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"url":"\/documentation\/yeofr\/yeofrbridge","type":"topic","kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/YEOFRBridge"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"stringForReturnCode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringForReturnCode:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"stringForReturnCode:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","preciseIdentifier":"c:@E@FRBridgeReturnCode","kind":"typeIdentifier","text":"FRBridgeReturnCode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rc"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1string(for:)\/title","value":"stringForReturnCode:","op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1string(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringForReturnCode:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode","op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","value":"YEOFRBridge","op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","value":[{"text":"YEOFRBridge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","value":[{"kind":"identifier","text":"YEOFRBridge"}],"op":"replace"}]}]}