{"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Getting started","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/QuickStart","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService"],"anchor":"Getting-started"},{"title":"Live recognition","anchor":"Live-recognition","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustUpdate","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceEvaluationResult","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustFrameResult","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/SDKFaceRecognitionResult"]},{"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/EnrollmentProgress","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/PoseTarget","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LightingPhaseConfig"],"anchor":"Enrolment","title":"Enrolment"},{"title":"Trust & liveness verdicts","anchor":"Trust--liveness-verdicts","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/SpoofVerdict","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/SpoofReason","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRDepthVerdict","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRDepthVerdictDetail","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFaceLivenessDetectorResult","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/InconclusiveReason","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/InvalidFrameReason","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/TrustDecisionPath","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionTrace","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/RecognitionLatchSnapshot"]},{"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceFramingStatus","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceFramingReason","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceRecognitionState","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"],"anchor":"Framing--engine-state","title":"Framing & engine state"},{"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRCameraSession","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustSession"],"anchor":"Lower-level-engine","title":"Lower-level engine"},{"title":"Configuring the trust signals","anchor":"Configuring-the-trust-signals","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionConfig","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionConfigurable","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionDefaults"]},{"title":"Encryption at rest","anchor":"Encryption-at-rest","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOEncryption","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/Cryptor","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/EncryptedBlob","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/CryptorError"]},{"generated":true,"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRTrueDepthState","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFaceLivenessDetector"]},{"generated":true,"title":"Protocols","anchor":"Protocols","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRTrueDepthHandling"]},{"generated":true,"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/KeychainKeyStore"],"title":"Structures","anchor":"Structures"},{"generated":true,"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKErrorDomain"],"title":"Variables","anchor":"Variables"},{"generated":true,"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFaceDetection"],"title":"Enumerations","anchor":"Enumerations"}],"hierarchy":{"paths":[[]]},"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YEOFR recognises an enrolled user from the front camera and rejects everyone"},{"type":"text","text":" "},{"type":"text","text":"else, fusing three signals into one trust decision: face recognition, a"},{"type":"text","text":" "},{"type":"text","text":"liveness CNN, and TrueDepth. The recognised path is "},{"type":"strong","inlineContent":[{"text":"arm64 device-only","type":"text"}]},{"type":"text","text":"."}]},{"name":"Version","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This documentation describes YEOFR "},{"inlineContent":[{"type":"text","text":"0.7.0"}],"type":"strong"},{"type":"text","text":". The package is"},{"type":"text","text":" "},{"type":"text","text":"pinned by exact version — see "},{"isActive":true,"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/QuickStart","type":"reference"},{"type":"text","text":"."}]}],"type":"aside","style":"note"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Most integrations need only "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService"},{"type":"text","text":" — a turnkey object that owns"},{"type":"text","text":" "},{"type":"text","text":"the engine, the camera, the fused-trust pipeline, the identity gate, and"},{"type":"text","text":" "},{"type":"text","text":"tracker persistence, and exposes two streams: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService\/updates()"},{"type":"text","text":" "},{"type":"text","text":"for live verdicts and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService\/enroll(name:poses:)"},{"type":"text","text":" for guided"},{"type":"text","text":" "},{"type":"text","text":"enrolment. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/QuickStart"},{"type":"text","text":"."}]}],"kind":"content"}],"kind":"symbol","metadata":{"roleHeading":"Framework","symbolKind":"module","title":"YEOFR","role":"collection","externalID":"YEOFR","modules":[{"name":"YEOFR"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr"]}],"abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"sections":[],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRDepthVerdict":{"title":"YEOFRDepthVerdict","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOFRDepthVerdict"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"YEOFRDepthVerdict"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRDepthVerdict","abstract":[{"type":"text","text":"The TrueDepth anti-spoof verdict for a frame: "},{"type":"codeVoice","code":".threeD"},{"type":"text","text":" (a real,"},{"type":"text","text":" "},{"type":"text","text":"volumetric face), "},{"type":"codeVoice","code":".flat"},{"type":"text","text":" (a planar surface such as a photo or screen),"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":".notDetermined"},{"type":"text","text":". Feed it to "},{"type":"reference","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustSession\/recordDepth(_:)","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/yeofr\/yeofrdepthverdict","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceTrustService":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceTrustService","kind":"identifier"}],"url":"\/documentation\/yeofr\/facetrustservice","kind":"symbol","navigatorTitle":[{"text":"FaceTrustService","kind":"identifier"}],"abstract":[{"type":"text","text":"Turnkey entry point for on-device face recognition with fused liveness"},{"type":"text","text":" "},{"type":"text","text":"and TrueDepth anti-spoofing."}],"title":"FaceTrustService","role":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRTrueDepthHandling":{"url":"\/documentation\/yeofr\/yeofrtruedepthhandling","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRTrueDepthHandling","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRTrueDepthHandling","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Adopt this on your own camera controller to drive TrueDepth","type":"text"},{"text":" ","type":"text"},{"text":"anti-spoofing yourself when you manage the ","type":"text"},{"code":"AVCaptureSession","type":"codeVoice"},{"text":" directly","type":"text"},{"text":" ","type":"text"},{"text":"instead of through ","type":"text"},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService","type":"reference","isActive":true},{"text":".","type":"text"}],"title":"YEOFRTrueDepthHandling","navigatorTitle":[{"text":"YEOFRTrueDepthHandling","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/LivenessFusionDefaults":{"title":"LivenessFusionDefaults","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessFusionDefaults","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"LivenessFusionDefaults","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionDefaults","url":"\/documentation\/yeofr\/livenessfusiondefaults","abstract":[{"type":"text","text":"The shipped default values for every "},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionConfigurable","isActive":true,"type":"reference"},{"type":"text","text":" "},{"text":"toggle, used when a consumer does not override them.","type":"text"}],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/SpoofVerdict":{"title":"SpoofVerdict","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpoofVerdict"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SpoofVerdict"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/SpoofVerdict","abstract":[{"type":"text","text":"The liveness CNN’s verdict for a frame: "},{"type":"codeVoice","code":".genuine"},{"type":"text","text":" or "},{"type":"codeVoice","code":".spoof"},{"type":"text","text":" (each"},{"type":"text","text":" "},{"type":"text","text":"with a confidence), or "},{"type":"codeVoice","code":".invalid"},{"type":"text","text":" when the frame is not evaluable."}],"url":"\/documentation\/yeofr\/spoofverdict","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRTrueDepthState":{"url":"\/documentation\/yeofr\/yeofrtruedepthstate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRTrueDepthState","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRTrueDepthState","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Mutable per-session state for a ","type":"text"},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRTrueDepthHandling","type":"reference","isActive":true},{"text":" conformer:","type":"text"},{"text":" ","type":"text"},{"text":"the in-flight Vision flag, last-run timing, and the rolling","type":"text"},{"text":" ","type":"text"},{"text":"flatness \/ no-face counters the depth analysis accumulates.","type":"text"}],"title":"YEOFRTrueDepthState","navigatorTitle":[{"text":"YEOFRTrueDepthState","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceFramingStatus":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceFramingStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FaceFramingStatus","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/yeofr\/faceframingstatus","title":"FaceFramingStatus","type":"topic","abstract":[{"text":"Whether the face is acceptably framed for recognition — ","type":"text"},{"code":".valid","type":"codeVoice"},{"text":", or","type":"text"},{"text":" ","type":"text"},{"code":".invalid","type":"codeVoice"},{"text":" with a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceFramingReason","type":"reference"},{"text":" to coach the user.","type":"text"}],"navigatorTitle":[{"text":"FaceFramingStatus","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOFRSDK"}],"navigatorTitle":[{"kind":"identifier","text":"YEOFRSDK"}],"abstract":[{"text":"YEOFR main entry point.","type":"text"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK","type":"topic","title":"YEOFRSDK","role":"symbol","url":"\/documentation\/yeofr\/yeofrsdk","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"abstract":[],"title":"YEOFRBridge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"url":"\/documentation\/yeofr\/yeofrbridge","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFaceLivenessDetector":{"url":"\/documentation\/yeofr\/yeofacelivenessdetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOFaceLivenessDetector"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFaceLivenessDetector","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"The TrueDepth anti-spoof detector: it inspects a face’s depth geometry","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and returns a "},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFaceLivenessDetectorResult","type":"reference","isActive":true},{"type":"text","text":" of live, spoof (with a"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/SpoofReason","type":"reference","isActive":true},{"type":"text","text":"), or inconclusive."}],"title":"YEOFaceLivenessDetector","navigatorTitle":[{"text":"YEOFaceLivenessDetector","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceFramingReason":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceFramingReason","role":"symbol","url":"\/documentation\/yeofr\/faceframingreason","navigatorTitle":[{"text":"FaceFramingReason","kind":"identifier"}],"type":"topic","title":"FaceFramingReason","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FaceFramingReason","kind":"identifier"}],"abstract":[{"text":"The specific framing problem that made a face ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceFramingStatus","type":"reference"},{"text":" ","type":"text"},{"text":"invalid, such as no face, too close, or too far.","type":"text"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/EnrollmentProgress":{"title":"EnrollmentProgress","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnrollmentProgress"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"EnrollmentProgress"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/EnrollmentProgress","url":"\/documentation\/yeofr\/enrollmentprogress","abstract":[{"text":"Progress for an in-flight enrolment capture. Yielded by","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService\/enroll(name:poses:)","isActive":true,"type":"reference"},{"text":" and the stream finishes once the","type":"text"},{"text":" ","type":"text"},{"text":"gallery is banked (or the capture can’t start).","type":"text"}],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/InconclusiveReason":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/InconclusiveReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InconclusiveReason"}],"abstract":[{"type":"text","text":"Why a liveness check could not reach a live-or-spoof verdict — for"},{"text":" ","type":"text"},{"text":"example still initialising or insufficient depth data this frame.","type":"text"}],"url":"\/documentation\/yeofr\/inconclusivereason","title":"InconclusiveReason","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InconclusiveReason"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/LivenessFusionConfig":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionConfig","role":"symbol","url":"\/documentation\/yeofr\/livenessfusionconfig","navigatorTitle":[{"kind":"identifier","text":"LivenessFusionConfig"}],"type":"topic","title":"LivenessFusionConfig","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LivenessFusionConfig"}],"abstract":[{"text":"A concrete, value-type ","type":"text"},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionConfigurable","isActive":true,"type":"reference"},{"text":" you can build and","type":"text"},{"text":" ","type":"text"},{"text":"hand to the trust pipeline to enable or disable individual signals.","type":"text"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRCameraSession":{"navigatorTitle":[{"text":"YEOFRCameraSession","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRCameraSession","abstract":[{"type":"text","text":"Manages the front-camera "},{"type":"codeVoice","code":"AVCaptureSession"},{"text":" and feeds frames — plus","type":"text"},{"text":" ","type":"text"},{"text":"TrueDepth, on supported devices — into the trust pipeline.","type":"text"}],"title":"YEOFRCameraSession","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/yeofr\/yeofrcamerasession","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"YEOFRCameraSession","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceTrustFrameResult":{"url":"\/documentation\/yeofr\/facetrustframeresult","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceTrustFrameResult","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustFrameResult","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Result of a single "},{"type":"codeVoice","code":"processFrame"},{"type":"text","text":" invocation. The detection half"},{"type":"text","text":" "},{"type":"text","text":"is the synchronous FR pass for this frame; the evaluation half is"},{"type":"text","text":" "},{"type":"text","text":"the "},{"inlineContent":[{"text":"latest","type":"text"}],"type":"emphasis"},{"text":" trust verdict (which may incorporate prior frames’","type":"text"},{"type":"text","text":" "},{"type":"text","text":"liveness results — the CNN runs asynchronously, so this frame’s"},{"type":"text","text":" "},{"type":"text","text":"CNN verdict typically lands ~1 frame later)."}],"type":"topic","title":"FaceTrustFrameResult","navigatorTitle":[{"text":"FaceTrustFrameResult","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceTrustSession/faceTrustStream()":{"title":"faceTrustStream()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceTrustStream","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"text":"FaceEvaluationResult","kind":"typeIdentifier","preciseIdentifier":"s:5YEOFR20FaceEvaluationResultV"},{"text":">","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustSession\/faceTrustStream()","abstract":[{"type":"text","text":"Subscribe to the rolling trust verdict stream. The current"},{"type":"text","text":" "},{"type":"codeVoice","code":"FaceEvaluationResult"},{"type":"text","text":" is yielded immediately on subscribe;"},{"type":"text","text":" "},{"type":"text","text":"subsequent values fire whenever observable state changes"},{"type":"text","text":" "},{"type":"text","text":"(trust, depth, liveness, face counts, anti-spoof signals)."}],"url":"\/documentation\/yeofr\/facetrustsession\/facetruststream()","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/QuickStart":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/QuickStart","kind":"article","role":"article","url":"\/documentation\/yeofr\/quickstart","title":"QuickStart","type":"topic","abstract":[{"type":"text","text":"Recognise the enrolled user and reject everyone else, in a few lines."}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/LivenessFusionTrace":{"title":"LivenessFusionTrace","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LivenessFusionTrace"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LivenessFusionTrace"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionTrace","abstract":[{"type":"text","text":"Public per-frame fusion trace for debug UI \/ CSV capture."},{"type":"text","text":" "},{"type":"text","text":"Mirrors the inputs that drove "},{"type":"codeVoice","code":"evaluateFusedTrust"},{"type":"text","text":" plus the"},{"type":"text","text":" "},{"type":"text","text":"hysteresis state, so a host can reconstruct exactly why the"},{"type":"text","text":" "},{"type":"text","text":"emitted "},{"type":"codeVoice","code":"trusted"},{"type":"text","text":" differs from the raw fused decision."}],"url":"\/documentation\/yeofr\/livenessfusiontrace","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceRecognitionState":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceRecognitionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceRecognitionState"}],"kind":"symbol","role":"symbol","url":"\/documentation\/yeofr\/facerecognitionstate","title":"FaceRecognitionState","abstract":[{"text":"The recognition engine’s lifecycle state — for example warming up,","type":"text"},{"text":" ","type":"text"},{"text":"ready, or in error — surfaced so the UI can gate capture until it is ready.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceRecognitionState"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFaceDetection":{"title":"YEOFaceDetection","abstract":[{"type":"text","text":"Neutral namespace for the public enrolment value types. (Caseless"},{"type":"text","text":" "},{"type":"text","text":"enum — never instantiated; it only carries the nested types whose"},{"type":"text","text":" "},{"type":"text","text":"fully-qualified names are part of the SDK’s public surface.)"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFaceDetection","kind":"identifier"}],"navigatorTitle":[{"text":"YEOFaceDetection","kind":"identifier"}],"url":"\/documentation\/yeofr\/yeofacedetection","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFaceDetection"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRVersionNumber":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRVersionNumber","fragments":[{"text":"YEOFRVersionNumber","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"YEOFRVersionNumber","url":"\/documentation\/yeofr\/yeofrversionnumber","type":"topic","abstract":[{"type":"text","text":"Project version number for YEOFR."}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/RecognitionLatchSnapshot":{"title":"RecognitionLatchSnapshot","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecognitionLatchSnapshot"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecognitionLatchSnapshot"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/RecognitionLatchSnapshot","abstract":[{"type":"text","text":"Diagnostic snapshot of the recognition latch’s internal state for"},{"type":"text","text":" "},{"type":"text","text":"one frame. Pushed by "},{"type":"codeVoice","code":"FaceTrustSession"},{"type":"text","text":" so the per-frame trace can"},{"type":"text","text":" "},{"type":"text","text":"surface "},{"inlineContent":[{"type":"text","text":"why"}],"type":"emphasis"},{"type":"text","text":" the latch is (or isn’t) admitting — the cold enter"},{"type":"text","text":" "},{"type":"text","text":"floor, whether it has been lowered, and the rolling enter-hit count."},{"type":"text","text":" "},{"type":"text","text":"Diagnostic-only: it never changes the emitted trust verdict."}],"url":"\/documentation\/yeofr\/recognitionlatchsnapshot","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/SpoofReason":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SpoofReason","kind":"identifier"}],"navigatorTitle":[{"text":"SpoofReason","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/SpoofReason","type":"topic","title":"SpoofReason","role":"symbol","url":"\/documentation\/yeofr\/spoofreason","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","type":"topic","title":"YEOFR","role":"collection","url":"\/documentation\/yeofr","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"title":"FRBridgeReturnCode","role":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRDepthVerdictDetail":{"title":"YEOFRDepthVerdictDetail","abstract":[{"type":"text","text":"The quantitative detail behind a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRDepthVerdict"},{"type":"text","text":": the model’s"},{"type":"text","text":" "},{"type":"text","text":"confidence and the measured face distance in metres."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOFRDepthVerdictDetail"}],"navigatorTitle":[{"kind":"identifier","text":"YEOFRDepthVerdictDetail"}],"url":"\/documentation\/yeofr\/yeofrdepthverdictdetail","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRDepthVerdictDetail"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceTrustService/updates()":{"url":"\/documentation\/yeofr\/facetrustservice\/updates()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updates"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:5YEOFR15FaceTrustUpdateV","kind":"typeIdentifier","text":"FaceTrustUpdate"},{"kind":"text","text":">"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService\/updates()","role":"symbol","kind":"symbol","abstract":[{"text":"Per-frame trust verdicts for the recognition UI. Call once and iterate;","type":"text"},{"type":"text","text":" "},{"text":"the stream finishes on ","type":"text"},{"type":"codeVoice","code":"stop()"},{"type":"text","text":". Newest-wins (the underlying camera"},{"type":"text","text":" "},{"type":"text","text":"stream drops stale frames), so a slow consumer can’t back up memory."}],"type":"topic","title":"updates()"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","abstract":[{"text":"A normalised status code returned by the recognition engine for an","type":"text"},{"text":" ","type":"text"},{"text":"operation such as detection, enrolment, or tracker loading.","type":"text"}],"title":"FRSDKReturnCode","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/yeofr\/frsdkreturncode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceTrustUpdate":{"url":"\/documentation\/yeofr\/facetrustupdate","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceTrustUpdate","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustUpdate","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"One per-frame trust readout, with the framing gate already applied — so the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"consumer renders a state, not a fusion of raw signals. Yielded by"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService\/updates()","isActive":true,"type":"reference"},{"text":".","type":"text"}],"title":"FaceTrustUpdate","navigatorTitle":[{"text":"FaceTrustUpdate","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceTrustSession/processFrame(buffer:)":{"title":"processFrame(buffer:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"buffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CVPixelBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"FaceTrustFrameResult","kind":"typeIdentifier","preciseIdentifier":"s:5YEOFR20FaceTrustFrameResultV"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustSession\/processFrame(buffer:)","abstract":[{"type":"text","text":"Run one frame through the fusion pipeline. The returned"},{"type":"text","text":" "},{"type":"codeVoice","code":"detection"},{"type":"text","text":" is sync and authoritative for this frame; the"},{"type":"text","text":" "},{"type":"text","text":"returned "},{"type":"codeVoice","code":"evaluation"},{"type":"text","text":" is the latest trust state (it may not"},{"type":"text","text":" "},{"type":"text","text":"include this frame’s CNN verdict yet since the CNN runs"},{"type":"text","text":" "},{"type":"text","text":"off-actor on a detached task)."}],"url":"\/documentation\/yeofr\/facetrustsession\/processframe(buffer:)","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/PoseTarget":{"title":"PoseTarget","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PoseTarget","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PoseTarget","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/PoseTarget","url":"\/documentation\/yeofr\/posetarget","abstract":[{"text":"Target head orientation for one slot of a gallery enrollment.","type":"text"}],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/TrustDecisionPath":{"title":"TrustDecisionPath","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrustDecisionPath","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"TrustDecisionPath","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/TrustDecisionPath","abstract":[{"type":"text","text":"Which rule admitted (or denied) trust for a frame, so a log reviewer"},{"type":"text","text":" "},{"type":"text","text":"sees the SDK’s ground-truth decision path. Records the "},{"inlineContent":[{"text":"admitting","type":"text"}],"type":"emphasis"},{"text":" ","type":"text"},{"type":"text","text":"reason; the trailing "},{"type":"codeVoice","code":"faceRecognitionMatch"},{"type":"text","text":" AND-gate can still drive"},{"type":"text","text":" "},{"type":"text","text":"the final "},{"type":"codeVoice","code":"trusted"},{"type":"text","text":" to false (logged separately via the FR-match column)."}],"url":"\/documentation\/yeofr\/trustdecisionpath","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/Cryptor":{"url":"\/documentation\/yeofr\/cryptor","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Cryptor"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/Cryptor","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Authenticated-encryption protocol the SDK funnels all sensitive","type":"text"},{"text":" ","type":"text"},{"text":"material through. Implementations must be safe to share across","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"threads ("},{"code":"Sendable","type":"codeVoice"},{"type":"text","text":") and must produce blobs whose "},{"code":"algorithmID","type":"codeVoice"},{"text":" ","type":"text"},{"text":"matches the byte returned by ","type":"text"},{"code":"algorithmID","type":"codeVoice"},{"text":".","type":"text"}],"title":"Cryptor","navigatorTitle":[{"kind":"identifier","text":"Cryptor"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/LivenessFusionConfigurable":{"title":"LivenessFusionConfigurable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessFusionConfigurable","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"LivenessFusionConfigurable","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LivenessFusionConfigurable","abstract":[{"type":"text","text":"The toggles the FR-trust pipeline reads to decide which signals — the"},{"type":"text","text":" "},{"type":"text","text":"liveness CNN and TrueDepth — contribute to a frame’s trust verdict."}],"url":"\/documentation\/yeofr\/livenessfusionconfigurable","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOEncryption":{"url":"\/documentation\/yeofr\/yeoencryption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"YEOEncryption"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOEncryption","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Selects how biometric payloads are encrypted before they are written to","type":"text"},{"text":" ","type":"text"},{"text":"disk — ","type":"text"},{"code":".plaintext","type":"codeVoice"},{"text":" (no encryption) or a consumer-supplied ","type":"text"},{"code":".custom","type":"codeVoice"},{"text":" cryptor.","type":"text"}],"title":"YEOEncryption","navigatorTitle":[{"kind":"identifier","text":"YEOEncryption"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/SDKFaceRecognitionResult":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/SDKFaceRecognitionResult","role":"symbol","url":"\/documentation\/yeofr\/sdkfacerecognitionresult","navigatorTitle":[{"text":"SDKFaceRecognitionResult","kind":"identifier"}],"title":"SDKFaceRecognitionResult","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDKFaceRecognitionResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Results for one frame"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceEvaluationResult":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceEvaluationResult","role":"symbol","url":"\/documentation\/yeofr\/faceevaluationresult","navigatorTitle":[{"text":"FaceEvaluationResult","kind":"identifier"}],"title":"FaceEvaluationResult","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceEvaluationResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Snapshot of every signal-fed value plus the accumulator’s"},{"type":"text","text":" "},{"type":"text","text":"derived trust verdict for one frame. Broadcast via"},{"type":"text","text":" "},{"type":"codeVoice","code":"faceTrustStream()"},{"type":"text","text":" after every "},{"type":"codeVoice","code":"valueUpdate(_:)"},{"type":"text","text":" that changes"},{"type":"text","text":" "},{"type":"text","text":"observable state."}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/EncryptedBlob":{"title":"EncryptedBlob","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EncryptedBlob","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"EncryptedBlob","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/EncryptedBlob","url":"\/documentation\/yeofr\/encryptedblob","abstract":[{"type":"text","text":"Versioned envelope around a cryptor’s payload. The "},{"code":"serialized()","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"representation is what gets persisted or sent over the wire; the"},{"type":"text","text":" "},{"type":"text","text":"in-memory form is what the SDK passes to \/ receives from a"},{"type":"text","text":" "},{"code":"Cryptor","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKErrorDomain":{"url":"\/documentation\/yeofr\/frsdkerrordomain","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRSDKErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKErrorDomain","role":"symbol","kind":"symbol","type":"topic","abstract":[],"title":"FRSDKErrorDomain","navigatorTitle":[{"kind":"identifier","text":"FRSDKErrorDomain"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFaceLivenessDetectorResult":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFaceLivenessDetectorResult","kind":"identifier"}],"navigatorTitle":[{"text":"YEOFaceLivenessDetectorResult","kind":"identifier"}],"abstract":[{"text":"The outcome of a TrueDepth liveness check: ","type":"text"},{"type":"codeVoice","code":".live"},{"text":", ","type":"text"},{"type":"codeVoice","code":".spoof"},{"type":"text","text":" (with a"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/SpoofReason","type":"reference"},{"text":" explaining the depth-geometry failure), or","type":"text"},{"type":"text","text":" "},{"code":".inconclusive","type":"codeVoice"},{"text":" (with an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/InconclusiveReason"},{"type":"text","text":")."}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFaceLivenessDetectorResult","type":"topic","title":"YEOFaceLivenessDetectorResult","role":"symbol","url":"\/documentation\/yeofr\/yeofacelivenessdetectorresult","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/KeychainKeyStore":{"url":"\/documentation\/yeofr\/keychainkeystore","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainKeyStore"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/KeychainKeyStore","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Generates and persists a symmetric encryption key in the Keychain,","type":"text"},{"text":" ","type":"text"},{"text":"creating one on first use and returning the same key on every call after.","type":"text"}],"title":"KeychainKeyStore","navigatorTitle":[{"kind":"identifier","text":"KeychainKeyStore"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/LightingPhaseConfig":{"navigatorTitle":[{"text":"LightingPhaseConfig","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/LightingPhaseConfig","title":"LightingPhaseConfig","abstract":[{"text":"Termination policy for the merged lighting phase — how long the","type":"text"},{"text":" ","type":"text"},{"text":"trailing-front “find new light” hunt runs and what ends it.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/yeofr\/lightingphaseconfig","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LightingPhaseConfig","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRVersionString":{"url":"\/documentation\/yeofr\/yeofrversionstring","fragments":[{"text":"YEOFRVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRVersionString","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Project version string for YEOFR.","type":"text"}],"title":"YEOFRVersionString"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceTrustSession/recordDepth(_:)":{"title":"recordDepth(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordDepth"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:5YEOFR17YEOFRDepthVerdictO","text":"YEOFRDepthVerdict"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustSession\/recordDepth(_:)","url":"\/documentation\/yeofr\/facetrustsession\/recorddepth(_:)","abstract":[{"type":"text","text":"Forward a TrueDepth verdict from the host’s depth pipeline"},{"type":"text","text":" "},{"type":"text","text":"into the evaluator. The session owns no camera or depth"},{"type":"text","text":" "},{"type":"text","text":"hardware — depth wiring stays in the host (per the SDK"},{"type":"text","text":" "},{"type":"text","text":"boundary), but the per-frame trust decision needs the verdict to"},{"type":"text","text":" "},{"type":"text","text":"drive the depth-primary gate."}],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceTrustService/enroll(name:poses:)":{"abstract":[{"type":"text","text":"Enrol "},{"code":"name","type":"codeVoice"},{"type":"text","text":" from the live camera and return a stream of capture"},{"type":"text","text":" "},{"type":"text","text":"progress. The existing frame loop drives the gallery walk; on completion"},{"type":"text","text":" "},{"type":"text","text":"the service persists the gallery, refreshes "},{"code":"enrolledName","type":"codeVoice"},{"type":"text","text":", resets the"},{"type":"text","text":" "},{"type":"text","text":"trust pipeline against the fresh gallery, and re-arms the identity gate —"},{"type":"text","text":" "},{"type":"text","text":"the consumer does none of that."}],"title":"enroll(name:poses:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enroll","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"poses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PoseTarget","preciseIdentifier":"s:5YEOFR10PoseTargetO"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"EnrollmentProgress","preciseIdentifier":"s:5YEOFR18EnrollmentProgressV"},{"kind":"text","text":">"}],"url":"\/documentation\/yeofr\/facetrustservice\/enroll(name:poses:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustService\/enroll(name:poses:)"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/InvalidFrameReason":{"title":"InvalidFrameReason","abstract":[{"type":"text","text":"Why a frame is not evaluable. Carried on "},{"code":"SpoofVerdict.invalid","type":"codeVoice"},{"type":"text","text":" so"},{"type":"text","text":" "},{"type":"text","text":"consumers can render distinct UX for “no face”, “too close”, etc.,"},{"type":"text","text":" "},{"type":"text","text":"instead of treating every non-evaluable frame as a spoof."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvalidFrameReason"}],"navigatorTitle":[{"kind":"identifier","text":"InvalidFrameReason"}],"url":"\/documentation\/yeofr\/invalidframereason","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/InvalidFrameReason"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/CryptorError":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/CryptorError","role":"symbol","url":"\/documentation\/yeofr\/cryptorerror","navigatorTitle":[{"text":"CryptorError","kind":"identifier"}],"title":"CryptorError","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CryptorError","kind":"identifier"}],"abstract":[{"text":"Typed failures surfaced to callers. Wrap any underlying CryptoKit","type":"text"},{"text":" ","type":"text"},{"text":"\/ CommonCrypto error so the public surface stays one error type.","type":"text"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FaceTrustSession":{"title":"FaceTrustSession","fragments":[{"kind":"keyword","text":"actor"},{"kind":"text","text":" "},{"text":"FaceTrustSession","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"FaceTrustSession","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustSession","url":"\/documentation\/yeofr\/facetrustsession","abstract":[{"type":"text","text":"A lower-level, camera-free trust pipeline: feed it frames with"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustSession\/processFrame(buffer:)","type":"reference","isActive":true},{"type":"text","text":" and read fused verdicts from"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FaceTrustSession\/faceTrustStream()","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/QuickStart"],"title":"Getting started","anchor":"Getting-started"},{"generated":true,"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge"],"title":"Classes","anchor":"Classes"},{"generated":true,"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKErrorDomain","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRVersionNumber","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRVersionString"],"title":"Variables","anchor":"Variables"},{"generated":true,"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"],"title":"Enumerations","anchor":"Enumerations"}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title","value":"YEOFRBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments","value":[{"text":"YEOFRBridge","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle","value":[{"kind":"identifier","text":"YEOFRBridge"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKErrorDomain\/title","value":"FRSDKErrorDomain"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKErrorDomain\/fragments","value":[{"text":"FRSDKErrorDomain","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}