{"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/s15BitwiseCopyableP","doc:\/\/com.youreyeonly.yeofr.YEOFR\/SQ","doc:\/\/com.youreyeonly.yeofr.YEOFR\/SH","doc:\/\/com.youreyeonly.yeofr.YEOFR\/SY","doc:\/\/com.youreyeonly.yeofr.YEOFR\/s8SendableP","doc:\/\/com.youreyeonly.yeofr.YEOFR\/s16SendableMetatypeP"]}],"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frbridgereturncode"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR"]]},"sections":[],"metadata":{"roleHeading":"Enumeration","externalID":"c:@E@FRBridgeReturnCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRBridgeReturnCode"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"role":"symbol","modules":[{"name":"YEOFR"}],"symbolKind":"enum","title":"FRBridgeReturnCode"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/OK","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/attributeNotDetected","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/badFileFormat","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/bufferSizeInvalid","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cameraIndexDoesNotExist","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cannotCreateFile","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cannotOpenFile","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionClosed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionFailed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/emptyTrackerData","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/faceNotFound","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/failed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/fileNotFound","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/idNotFound","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/imageTooSmall","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/insufficientBufferSize","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/insufficientTrackerMemoryLimit","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/invalidArgument","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/invalidTemplate","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/ioError","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/ipInitFailed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/needServerActivation","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/notActivated","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/outOfMemory","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/outTrackerNull","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/parameterNotFound","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/platformNotLicensed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/pluginNoPermission","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/pluginNotLoaded","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/setParametersFailed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/syntaxError","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/tensorflowNotInitialized","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerBufferMallocFailed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerExists","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerIsNull","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unknownAttribute","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedFileVersion","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedImageExtension","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedTemplateVersion"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/init(rawValue:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/Equatable-Implementations","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/RawRepresentable-Implementations"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRBridgeReturnCode"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","title":"FRBridgeReturnCode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/tensorflowNotInitialized":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/tensorflowNotInitialized","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode\/tensorflownotinitialized","title":"FRBridgeReturnCode.tensorflowNotInitialized","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tensorflowNotInitialized"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeTensorflowNotInitialized"}]},"doc://com.youreyeonly.yeofr.YEOFR/s16SendableMetatypeP":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/outTrackerNull":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeOutTrackerNull"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outTrackerNull"}],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/outtrackernull","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/outTrackerNull","type":"topic","kind":"symbol","title":"FRBridgeReturnCode.outTrackerNull"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/invalidArgument":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeInvalidArgument"}],"title":"FRBridgeReturnCode.invalidArgument","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidArgument"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/invalidArgument","type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode\/invalidargument","abstract":[]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/connectionClosed":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionClosed","abstract":[],"type":"topic","title":"FRBridgeReturnCode.connectionClosed","url":"\/documentation\/yeofr\/frbridgereturncode\/connectionclosed","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionClosed"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeConnectionClosed"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/attributeNotDetected":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/attributeNotDetected","abstract":[],"type":"topic","title":"FRBridgeReturnCode.attributeNotDetected","url":"\/documentation\/yeofr\/frbridgereturncode\/attributenotdetected","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributeNotDetected"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeAttributeNotDetected"}]},"doc://com.youreyeonly.yeofr.YEOFR/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/SH","type":"unresolvable"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/invalidTemplate":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/invalidTemplate","abstract":[],"type":"topic","title":"FRBridgeReturnCode.invalidTemplate","url":"\/documentation\/yeofr\/frbridgereturncode\/invalidtemplate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidTemplate"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeInvalidTemplate"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/OK":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/OK","abstract":[],"type":"topic","title":"FRBridgeReturnCode.OK","url":"\/documentation\/yeofr\/frbridgereturncode\/ok","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeOK"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/idNotFound":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/idNotFound","abstract":[],"type":"topic","title":"FRBridgeReturnCode.idNotFound","url":"\/documentation\/yeofr\/frbridgereturncode\/idnotfound","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idNotFound"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeIdNotFound"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/unknownAttribute":{"abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unknownAttribute","title":"FRBridgeReturnCode.unknownAttribute","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FRBridgeReturnCodeUnknownAttribute","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode\/unknownattribute","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownAttribute","kind":"identifier"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/cannotCreateFile":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cannotCreateFile","abstract":[],"type":"topic","title":"FRBridgeReturnCode.cannotCreateFile","url":"\/documentation\/yeofr\/frbridgereturncode\/cannotcreatefile","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotCreateFile"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeCannotCreateFile"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/trackerIsNull":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerIsNull","abstract":[],"type":"topic","title":"FRBridgeReturnCode.trackerIsNull","url":"\/documentation\/yeofr\/frbridgereturncode\/trackerisnull","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackerIsNull"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeTrackerIsNull"}]},"doc://com.youreyeonly.yeofr.YEOFR/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/s8SendableP","type":"unresolvable"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/insufficientBufferSize":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/insufficientBufferSize","abstract":[],"type":"topic","title":"FRBridgeReturnCode.insufficientBufferSize","url":"\/documentation\/yeofr\/frbridgereturncode\/insufficientbuffersize","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insufficientBufferSize"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeInsufficientBufferSize"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/Equatable-Implementations":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/Equatable-Implementations","abstract":[],"type":"topic","title":"Equatable Implementations","url":"\/documentation\/yeofr\/frbridgereturncode\/equatable-implementations","kind":"article","role":"collectionGroup"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/fileNotFound":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/fileNotFound","abstract":[],"type":"topic","title":"FRBridgeReturnCode.fileNotFound","url":"\/documentation\/yeofr\/frbridgereturncode\/filenotfound","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileNotFound"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeFileNotFound"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/trackerExists":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerExists","abstract":[],"type":"topic","title":"FRBridgeReturnCode.trackerExists","url":"\/documentation\/yeofr\/frbridgereturncode\/trackerexists","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackerExists"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeTrackerExists"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/trackerBufferMallocFailed":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerBufferMallocFailed","abstract":[],"type":"topic","title":"FRBridgeReturnCode.trackerBufferMallocFailed","url":"\/documentation\/yeofr\/frbridgereturncode\/trackerbuffermallocfailed","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackerBufferMallocFailed"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeTrackerBufferMallocFailed"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/badFileFormat":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/badFileFormat","abstract":[],"type":"topic","title":"FRBridgeReturnCode.badFileFormat","url":"\/documentation\/yeofr\/frbridgereturncode\/badfileformat","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badFileFormat"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeBadFileFormat"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/setParametersFailed":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/setParametersFailed","abstract":[],"type":"topic","title":"FRBridgeReturnCode.setParametersFailed","url":"\/documentation\/yeofr\/frbridgereturncode\/setparametersfailed","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"setParametersFailed"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeSetParametersFailed"}]},"doc://com.youreyeonly.yeofr.YEOFR/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/SY","type":"unresolvable"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/bufferSizeInvalid":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/bufferSizeInvalid","abstract":[],"type":"topic","title":"FRBridgeReturnCode.bufferSizeInvalid","url":"\/documentation\/yeofr\/frbridgereturncode\/buffersizeinvalid","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferSizeInvalid"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeBufferSizeInvalid"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/unsupportedTemplateVersion":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedTemplateVersion","abstract":[],"type":"topic","title":"FRBridgeReturnCode.unsupportedTemplateVersion","url":"\/documentation\/yeofr\/frbridgereturncode\/unsupportedtemplateversion","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedTemplateVersion"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedTemplateVersion"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/init(rawValue:)":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/init(rawValue:)","abstract":[],"type":"topic","title":"init(rawValue:)","url":"\/documentation\/yeofr\/frbridgereturncode\/init(rawvalue:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/ipInitFailed":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/ipInitFailed","abstract":[],"type":"topic","title":"FRBridgeReturnCode.ipInitFailed","url":"\/documentation\/yeofr\/frbridgereturncode\/ipinitfailed","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ipInitFailed"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeIPInitFailed"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/syntaxError":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/syntaxError","abstract":[],"type":"topic","title":"FRBridgeReturnCode.syntaxError","url":"\/documentation\/yeofr\/frbridgereturncode\/syntaxerror","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"syntaxError"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeSyntaxError"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/emptyTrackerData":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/emptyTrackerData","abstract":[],"type":"topic","title":"FRBridgeReturnCode.emptyTrackerData","url":"\/documentation\/yeofr\/frbridgereturncode\/emptytrackerdata","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyTrackerData"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeEmptyTrackerData"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/unsupportedFileVersion":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedFileVersion","abstract":[],"type":"topic","title":"FRBridgeReturnCode.unsupportedFileVersion","url":"\/documentation\/yeofr\/frbridgereturncode\/unsupportedfileversion","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedFileVersion"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedFileVersion"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/pluginNotLoaded":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/pluginNotLoaded","abstract":[],"type":"topic","title":"FRBridgeReturnCode.pluginNotLoaded","url":"\/documentation\/yeofr\/frbridgereturncode\/pluginnotloaded","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginNotLoaded"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodePluginNotLoaded"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/ioError":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeIOError"}],"title":"FRBridgeReturnCode.ioError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ioError"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/ioError","type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode\/ioerror","abstract":[]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/parameterNotFound":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/parameterNotFound","abstract":[],"type":"topic","title":"FRBridgeReturnCode.parameterNotFound","url":"\/documentation\/yeofr\/frbridgereturncode\/parameternotfound","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"parameterNotFound"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeParameterNotFound"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/pluginNoPermission":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/pluginNoPermission","abstract":[],"type":"topic","title":"FRBridgeReturnCode.pluginNoPermission","url":"\/documentation\/yeofr\/frbridgereturncode\/pluginnopermission","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginNoPermission"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodePluginNoPermission"}]},"doc://com.youreyeonly.yeofr.YEOFR/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/s15BitwiseCopyableP","type":"unresolvable"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/imageTooSmall":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/imageTooSmall","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode\/imagetoosmall","title":"FRBridgeReturnCode.imageTooSmall","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageTooSmall"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeImageTooSmall"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/outOfMemory":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeOutOfMemory"}],"title":"FRBridgeReturnCode.outOfMemory","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outOfMemory"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/outOfMemory","type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode\/outofmemory","abstract":[]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/insufficientTrackerMemoryLimit":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/insufficientTrackerMemoryLimit","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode\/insufficienttrackermemorylimit","title":"FRBridgeReturnCode.insufficientTrackerMemoryLimit","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insufficientTrackerMemoryLimit"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeInsufficientTrackerMemoryLimit"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/platformNotLicensed":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/platformNotLicensed","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode\/platformnotlicensed","title":"FRBridgeReturnCode.platformNotLicensed","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"platformNotLicensed"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodePlatformNotLicensed"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol","title":"YEOFR","url":"\/documentation\/yeofr","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"role":"collection","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/unsupportedImageExtension":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedImageExtension"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedImageExtension"}],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/unsupportedimageextension","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedImageExtension","type":"topic","title":"FRBridgeReturnCode.unsupportedImageExtension","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/failed":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeFailed"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/failed","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/failed","type":"topic","kind":"symbol","title":"FRBridgeReturnCode.failed"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/notActivated":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeNotActivated"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notActivated"}],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/notactivated","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/notActivated","type":"topic","kind":"symbol","title":"FRBridgeReturnCode.notActivated"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/faceNotFound":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeFaceNotFound"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceNotFound"}],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/facenotfound","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/faceNotFound","type":"topic","kind":"symbol","title":"FRBridgeReturnCode.faceNotFound"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/needServerActivation":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeNeedServerActivation"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"needServerActivation"}],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/needserveractivation","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/needServerActivation","type":"topic","kind":"symbol","title":"FRBridgeReturnCode.needServerActivation"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/cannotOpenFile":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeCannotOpenFile"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotOpenFile"}],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/cannotopenfile","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cannotOpenFile","type":"topic","kind":"symbol","title":"FRBridgeReturnCode.cannotOpenFile"},"doc://com.youreyeonly.yeofr.YEOFR/SQ":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","url":"\/documentation\/yeofr\/frbridgereturncode\/rawrepresentable-implementations","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/RawRepresentable-Implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/connectionFailed":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeConnectionFailed"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionFailed"}],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/connectionfailed","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionFailed","type":"topic","kind":"symbol","title":"FRBridgeReturnCode.connectionFailed"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/cameraIndexDoesNotExist":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeCameraIndexDoesNotExist"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIndexDoesNotExist"}],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/cameraindexdoesnotexist","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cameraIndexDoesNotExist","type":"topic","kind":"symbol","title":"FRBridgeReturnCode.cameraIndexDoesNotExist"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"FRBridgeReturnCode","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/OK","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/attributeNotDetected","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/badFileFormat","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/bufferSizeInvalid","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cameraIndexDoesNotExist","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cannotCreateFile","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cannotOpenFile","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionClosed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionFailed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/emptyTrackerData","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/faceNotFound","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/failed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/fileNotFound","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/idNotFound","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/imageTooSmall","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/insufficientBufferSize","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/insufficientTrackerMemoryLimit","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/invalidArgument","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/invalidTemplate","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/ioError","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/ipInitFailed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/needServerActivation","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/notActivated","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/outOfMemory","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/outTrackerNull","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/parameterNotFound","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/platformNotLicensed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/pluginNoPermission","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/pluginNotLoaded","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/setParametersFailed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/syntaxError","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/tensorflowNotInitialized","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerBufferMallocFailed","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerExists","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerIsNull","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unknownAttribute","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedFileVersion","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedImageExtension","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedTemplateVersion"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"FRBridgeReturnCode","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle"},{"value":"FRBridgeReturnCodeTensorflowNotInitialized","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1tensorflowNotInitialized\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeTensorflowNotInitialized"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1tensorflowNotInitialized\/fragments"},{"value":"FRBridgeReturnCodeOutTrackerNull","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1outTrackerNull\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeOutTrackerNull"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1outTrackerNull\/fragments"},{"value":"FRBridgeReturnCodeInvalidArgument","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1invalidArgument\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeInvalidArgument"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1invalidArgument\/fragments"},{"value":"FRBridgeReturnCodeConnectionClosed","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1connectionClosed\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeConnectionClosed"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1connectionClosed\/fragments"},{"value":"FRBridgeReturnCodeAttributeNotDetected","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1attributeNotDetected\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeAttributeNotDetected"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1attributeNotDetected\/fragments"},{"value":"FRBridgeReturnCodeInvalidTemplate","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1invalidTemplate\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeInvalidTemplate"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1invalidTemplate\/fragments"},{"value":"FRBridgeReturnCodeOK","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1OK\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeOK"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1OK\/fragments"},{"value":"FRBridgeReturnCodeIdNotFound","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1idNotFound\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeIdNotFound"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1idNotFound\/fragments"},{"value":"FRBridgeReturnCodeUnknownAttribute","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unknownAttribute\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeUnknownAttribute"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unknownAttribute\/fragments"},{"value":"FRBridgeReturnCodeCannotCreateFile","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cannotCreateFile\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeCannotCreateFile"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cannotCreateFile\/fragments"},{"value":"FRBridgeReturnCodeTrackerIsNull","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1trackerIsNull\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeTrackerIsNull"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1trackerIsNull\/fragments"},{"value":"FRBridgeReturnCodeInsufficientBufferSize","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1insufficientBufferSize\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeInsufficientBufferSize"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1insufficientBufferSize\/fragments"},{"value":"FRBridgeReturnCodeFileNotFound","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1fileNotFound\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeFileNotFound"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1fileNotFound\/fragments"},{"value":"FRBridgeReturnCodeTrackerExists","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1trackerExists\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeTrackerExists"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1trackerExists\/fragments"},{"value":"FRBridgeReturnCodeTrackerBufferMallocFailed","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1trackerBufferMallocFailed\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeTrackerBufferMallocFailed"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1trackerBufferMallocFailed\/fragments"},{"value":"FRBridgeReturnCodeBadFileFormat","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1badFileFormat\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeBadFileFormat"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1badFileFormat\/fragments"},{"value":"FRBridgeReturnCodeSetParametersFailed","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1setParametersFailed\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeSetParametersFailed"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1setParametersFailed\/fragments"},{"value":"FRBridgeReturnCodeBufferSizeInvalid","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1bufferSizeInvalid\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeBufferSizeInvalid"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1bufferSizeInvalid\/fragments"},{"value":"FRBridgeReturnCodeUnsupportedTemplateVersion","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedTemplateVersion\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedTemplateVersion"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedTemplateVersion\/fragments"},{"value":"FRBridgeReturnCodeIPInitFailed","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1ipInitFailed\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeIPInitFailed"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1ipInitFailed\/fragments"},{"value":"FRBridgeReturnCodeSyntaxError","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1syntaxError\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeSyntaxError"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1syntaxError\/fragments"},{"value":"FRBridgeReturnCodeEmptyTrackerData","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1emptyTrackerData\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeEmptyTrackerData"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1emptyTrackerData\/fragments"},{"value":"FRBridgeReturnCodeUnsupportedFileVersion","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedFileVersion\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedFileVersion"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedFileVersion\/fragments"},{"value":"FRBridgeReturnCodePluginNotLoaded","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1pluginNotLoaded\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodePluginNotLoaded"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1pluginNotLoaded\/fragments"},{"value":"FRBridgeReturnCodeIOError","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1ioError\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeIOError"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1ioError\/fragments"},{"value":"FRBridgeReturnCodeParameterNotFound","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1parameterNotFound\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeParameterNotFound"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1parameterNotFound\/fragments"},{"value":"FRBridgeReturnCodePluginNoPermission","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1pluginNoPermission\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodePluginNoPermission"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1pluginNoPermission\/fragments"},{"value":"FRBridgeReturnCodeImageTooSmall","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1imageTooSmall\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeImageTooSmall"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1imageTooSmall\/fragments"},{"value":"FRBridgeReturnCodeOutOfMemory","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1outOfMemory\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeOutOfMemory"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1outOfMemory\/fragments"},{"value":"FRBridgeReturnCodeInsufficientTrackerMemoryLimit","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1insufficientTrackerMemoryLimit\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeInsufficientTrackerMemoryLimit"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1insufficientTrackerMemoryLimit\/fragments"},{"value":"FRBridgeReturnCodePlatformNotLicensed","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1platformNotLicensed\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodePlatformNotLicensed"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1platformNotLicensed\/fragments"},{"value":"FRBridgeReturnCodeUnsupportedImageExtension","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedImageExtension\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedImageExtension"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedImageExtension\/fragments"},{"value":"FRBridgeReturnCodeFailed","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1failed\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeFailed"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1failed\/fragments"},{"value":"FRBridgeReturnCodeNotActivated","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1notActivated\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeNotActivated"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1notActivated\/fragments"},{"value":"FRBridgeReturnCodeFaceNotFound","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1faceNotFound\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeFaceNotFound"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1faceNotFound\/fragments"},{"value":"FRBridgeReturnCodeNeedServerActivation","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1needServerActivation\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeNeedServerActivation"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1needServerActivation\/fragments"},{"value":"FRBridgeReturnCodeCannotOpenFile","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cannotOpenFile\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeCannotOpenFile"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cannotOpenFile\/fragments"},{"value":"FRBridgeReturnCodeConnectionFailed","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1connectionFailed\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeConnectionFailed"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1connectionFailed\/fragments"},{"value":"FRBridgeReturnCodeCameraIndexDoesNotExist","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cameraIndexDoesNotExist\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeCameraIndexDoesNotExist"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cameraIndexDoesNotExist\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}