{"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR"]]},"primaryContentSections":[{"kind":"content","content":[{"anchor":"1-Add-the-SDK","type":"heading","text":"1. Add the SDK","level":2},{"type":"paragraph","inlineContent":[{"text":"Add the ","type":"text"},{"type":"strong","inlineContent":[{"text":"YEOFR","type":"text"}]},{"text":" Swift package","type":"text"},{"text":" ","type":"text"},{"text":"(","type":"text"},{"type":"codeVoice","code":"https:\/\/github.com\/YEOMessaging\/YEOFR-SPM"},{"text":") to your project, pinned to","type":"text"},{"text":" ","type":"text"},{"text":"exact version ","type":"text"},{"type":"strong","inlineContent":[{"text":"0.7.1","type":"text"}]},{"text":", then ","type":"text"},{"type":"codeVoice","code":"import YEOFR"},{"text":". The binary is ","type":"text"},{"type":"strong","inlineContent":[{"text":"arm64","type":"text"},{"text":" ","type":"text"},{"text":"device-only","type":"text"}]},{"text":" — it does not run on the simulator.","type":"text"}]},{"anchor":"2-Pilot-unlock-for-non-YEO-bundle-IDs","type":"heading","text":"2. Pilot unlock for non-YEO bundle IDs","level":2},{"type":"paragraph","inlineContent":[{"text":"YEOFR is gated to YEO-owned apps by default; a non-YEO bundle id aborts on","type":"text"},{"text":" ","type":"text"},{"text":"construction. Evaluation customers get a ","type":"text"},{"type":"strong","inlineContent":[{"text":"temporary unlock code","type":"text"}]},{"text":" that","type":"text"},{"text":" ","type":"text"},{"text":"bypasses the gate during a fixed pilot window — email","type":"text"},{"text":" ","type":"text"},{"type":"strong","inlineContent":[{"text":"christo@yeomessaging.com","type":"text"}]},{"text":" to request one. Pass it to the initializer","type":"text"},{"text":" ","type":"text"},{"text":"(step 3). YEO-owned apps pass the gate natively.","type":"text"}]},{"anchor":"3-Drive-everything-with-FaceTrustService","type":"heading","text":"3. Drive everything with `FaceTrustService`","level":2},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustService","isActive":true,"type":"reference"},{"text":" is the turnkey entry point. It owns the engine, the","type":"text"},{"text":" ","type":"text"},{"text":"camera, the fused-trust pipeline (face recognition + liveness CNN +","type":"text"},{"text":" ","type":"text"},{"text":"TrueDepth), the identity gate, and tracker persistence, and exposes two","type":"text"},{"text":" ","type":"text"},{"text":"streams: one for live trust verdicts and one for guided enrolment.","type":"text"}]},{"code":["import YEOFR","","let service = FaceTrustService(pilotUnlockCode: \"YOUR-PILOT-CODE\")","","\/\/ Attach the preview to an AVCaptureVideoPreviewLayer:","\/\/   previewLayer.session = service.previewSession","","try await service.start()    \/\/ warm-up, restore enrolment, arm gate, start camera"],"type":"codeListing","syntax":"swift"},{"anchor":"4-Enrol-a-face","type":"heading","text":"4. Enrol a face","level":2},{"type":"paragraph","inlineContent":[{"code":"enroll(name:)","type":"codeVoice"},{"text":" runs a short guided capture, persists the gallery, and","type":"text"},{"text":" ","type":"text"},{"text":"re-arms the identity gate. Iterate the returned stream to coach the user:","type":"text"}]},{"code":["for await step in service.enroll(name: \"Alice\") {","    switch step.phase {","    case .capturing: show(step.prompt, progress: step.poseProgress)","    case .completed: dismiss()","    case .failed:    show(step.prompt)","    @unknown default: break","    }","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"A single front pose is enough to separate the enrolled user from other"},{"type":"text","text":" "},{"type":"text","text":"people. Pass "},{"code":"poses: PoseTarget.lightingAwareGallerySequence","type":"codeVoice"},{"type":"text","text":" to also"},{"type":"text","text":" "},{"type":"text","text":"capture off-axis poses + a lighting pass, which improves recall as the"},{"text":" ","type":"text"},{"text":"user turns their head.","type":"text"}],"type":"paragraph"},{"anchor":"5-Run-live-recognition","text":"5. Run live recognition","level":2,"type":"heading"},{"type":"codeListing","syntax":"swift","code":["for await update in service.updates() {","    switch update.status {","    case .trusted:    badge(\"TRUSTED — \\(update.matchedName ?? \"\")\", .green)","    case .notTrusted: badge(\"NOT TRUSTED\", .red)","    case .badFraming: badge(\"ADJUST FRAMING\", .orange)","    case .noFace:     badge(\"NO FACE\", .gray)","    @unknown default: break","    }","    \/\/ update.livenessGenuine \/ update.depthIsThreeD are the contributing signals.","}"]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"update.status == .trusted"},{"text":" already fuses face recognition, liveness, and","type":"text"},{"text":" ","type":"text"},{"text":"TrueDepth, with framing applied — you never pick a similarity threshold,","type":"text"},{"text":" ","type":"text"},{"text":"and you never touch the identity gate (forgetting it would collapse trust","type":"text"},{"text":" ","type":"text"},{"text":"to liveness + depth, so any live face would pass). The enrolled gallery is","type":"text"},{"text":" ","type":"text"},{"text":"saved across launches automatically; ","type":"text"},{"type":"codeVoice","code":"service.enrolledName"},{"text":" reflects who is","type":"text"},{"text":" ","type":"text"},{"text":"enrolled.","type":"text"}]},{"level":2,"text":"See also","anchor":"See-also","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A complete, runnable SwiftUI app lives in the package’s "},{"code":"Examples\/FRPilot","type":"codeVoice"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustService"},{"type":"text","text":" — full API."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustUpdate"},{"type":"text","text":" \/ "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/EnrollmentProgress"},{"type":"text","text":" — the stream payloads."}]}]}],"type":"unorderedList"}]}],"variants":[{"paths":["\/documentation\/yeofr\/quickstart"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/quickstart"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Recognise the enrolled user and reject everyone else, in a few lines."}],"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustService"],"anchor":"Getting-started","title":"Getting started","generated":true}],"kind":"article","metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"YEOFR"}],"title":"QuickStart"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/QuickStart","interfaceLanguage":"swift"},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FaceTrustService":{"title":"FaceTrustService","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustService","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Turnkey entry point for on-device face recognition with fused liveness"},{"text":" ","type":"text"},{"text":"and TrueDepth anti-spoofing.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceTrustService","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceTrustService"}],"url":"\/documentation\/yeofr\/facetrustservice"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FaceTrustService/updates()":{"url":"\/documentation\/yeofr\/facetrustservice\/updates()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updates","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:5YEOFR15FaceTrustUpdateV","text":"FaceTrustUpdate","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustService\/updates()","abstract":[{"text":"Per-frame trust verdicts for the recognition UI. Call once and iterate;","type":"text"},{"text":" ","type":"text"},{"text":"the stream finishes on ","type":"text"},{"code":"stop()","type":"codeVoice"},{"text":". Newest-wins (the underlying camera","type":"text"},{"text":" ","type":"text"},{"text":"stream drops stale frames), so a slow consumer can’t back up memory.","type":"text"}],"role":"symbol","title":"updates()","type":"topic"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FaceTrustService/enroll(name:poses:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enroll","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"poses","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:5YEOFR10PoseTargetO","text":"PoseTarget","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:5YEOFR18EnrollmentProgressV","text":"EnrollmentProgress","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustService\/enroll(name:poses:)","abstract":[{"text":"Enrol ","type":"text"},{"code":"name","type":"codeVoice"},{"text":" from the live camera and return a stream of capture","type":"text"},{"text":" ","type":"text"},{"text":"progress. The existing frame loop drives the gallery walk; on completion","type":"text"},{"text":" ","type":"text"},{"text":"the service persists the gallery, refreshes ","type":"text"},{"code":"enrolledName","type":"codeVoice"},{"text":", resets the","type":"text"},{"text":" ","type":"text"},{"text":"trust pipeline against the fresh gallery, and re-arms the identity gate —","type":"text"},{"text":" ","type":"text"},{"text":"the consumer does none of that.","type":"text"}],"role":"symbol","url":"\/documentation\/yeofr\/facetrustservice\/enroll(name:poses:)","title":"enroll(name:poses:)"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"title":"YEOFR","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"type":"topic","url":"\/documentation\/yeofr"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FaceTrustUpdate":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceTrustUpdate","kind":"identifier"}],"navigatorTitle":[{"text":"FaceTrustUpdate","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/yeofr\/facetrustupdate","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustUpdate","abstract":[{"text":"One per-frame trust readout, with the framing gate already applied — so the","type":"text"},{"text":" ","type":"text"},{"text":"consumer renders a state, not a fusion of raw signals. Yielded by","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustService\/updates()","type":"reference"},{"text":".","type":"text"}],"title":"FaceTrustUpdate","type":"topic"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/EnrollmentProgress":{"type":"topic","navigatorTitle":[{"text":"EnrollmentProgress","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EnrollmentProgress","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/EnrollmentProgress","abstract":[{"text":"Progress for an in-flight enrolment capture. Yielded by","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FaceTrustService\/enroll(name:poses:)","isActive":true,"type":"reference"},{"text":" and the stream finishes once the","type":"text"},{"text":" ","type":"text"},{"text":"gallery is banked (or the capture can’t start).","type":"text"}],"role":"symbol","url":"\/documentation\/yeofr\/enrollmentprogress","title":"EnrollmentProgress"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":[],"generated":true,"title":"Getting started","anchor":"Getting-started"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}