{"variants":[{"paths":["\/documentation\/yeofr\/yeofrbridge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/yeofrbridge"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/activate(withKey:dataPath:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/checkPNGImageMatchesTracker(_:tracker:outIsSingle:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/clearTracker(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configure(withThreads:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configure(withThreads:internalResizeWidth:detectionThreshold:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configureShoulderSurfing(withResizeWidth:detectionThreshold:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/createTracker(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/detectFaces(inPNGData:tracker:outDetectedCount:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/freeTracker(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getHardwareID(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getLicenseInfo(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getTrackerData(_:outData:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/learnCurrentFace(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/loadTracker(from:outTracker:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/setName(_:faceID:name:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/string(for:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR"]]},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/objc(pl)NSObject","doc:\/\/com.youreyeonly.yeofr.YEOFR\/s7CVarArgP","doc:\/\/com.youreyeonly.yeofr.YEOFR\/s28CustomDebugStringConvertibleP","doc:\/\/com.youreyeonly.yeofr.YEOFR\/s23CustomStringConvertibleP","doc:\/\/com.youreyeonly.yeofr.YEOFR\/SQ","doc:\/\/com.youreyeonly.yeofr.YEOFR\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","metadata":{"title":"YEOFRBridge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"YEOFRBridge"}],"modules":[{"name":"YEOFR"}],"externalID":"c:objc(cs)YEOFRBridge"},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/setName(_:faceID:name:error:)":{"abstract":[{"type":"text","text":"Assign a name (tag) to a face ID in the tracker."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/setName(_:faceID:name:error:)","title":"setName(_:faceID:name:error:)","url":"\/documentation\/yeofr\/yeofrbridge\/setname(_:faceid:name:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"setName:faceID:name:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/SQ","title":"Swift.Equatable"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/getLicenseInfo(_:error:)":{"title":"getLicenseInfo(_:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLicenseInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":"?>?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"}],"url":"\/documentation\/yeofr\/yeofrbridge\/getlicenseinfo(_:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getLicenseInfo(_:error:)","abstract":[{"type":"text","text":"Retrieve license information from the SDK (optional)."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"getLicenseInfo:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/configureShoulderSurfing(withResizeWidth:detectionThreshold:error:)":{"title":"configureShoulderSurfing(withResizeWidth:detectionThreshold:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureShoulderSurfing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withResizeWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode","kind":"typeIdentifier"}],"url":"\/documentation\/yeofr\/yeofrbridge\/configureshouldersurfing(withresizewidth:detectionthreshold:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configureShoulderSurfing(withResizeWidth:detectionThreshold:error:)","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"configureShoulderSurfingWithResizeWidth:detectionThreshold:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/SH"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"type":"topic","title":"YEOFR","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/freeTracker(_:error:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Free a tracker."},{"type":"text","text":" "},{"type":"text","text":"USE FREE TRACKER when tearing down to re enroll."}],"type":"topic","title":"freeTracker(_:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"freeTracker","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode","kind":"typeIdentifier"}],"url":"\/documentation\/yeofr\/yeofrbridge\/freetracker(_:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/freeTracker(_:error:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"freeTracker:error:","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge":{"url":"\/documentation\/yeofr\/yeofrbridge","navigatorTitle":[{"text":"YEOFRBridge","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"YEOFRBridge"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge","kind":"symbol","title":"YEOFRBridge","abstract":[],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/activate(withKey:dataPath:error:)":{"title":"activate(withKey:dataPath:error:)","role":"symbol","url":"\/documentation\/yeofr\/yeofrbridge\/activate(withkey:datapath:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/activate(withKey:dataPath:error:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier","text":"FRSDKReturnCode"}],"abstract":[{"text":"Activate and initialize the SDK.","type":"text"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"activateWithKey:dataPath:error:"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Process a single ARGB32 frame through the SDK pipeline."}],"type":"topic","title":"processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"processFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:SV"},{"text":", ","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"scanLine","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracker"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needFaceRect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ratio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outIDs"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outNames"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outRects"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"outDetectedCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier","text":"FRSDKReturnCode"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)","url":"\/documentation\/yeofr\/yeofrbridge\/processframe(withbuffer:width:height:scanline:tracker:needfacerect:ratio:outids:outnames:outrects:outdetectedcount:error:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/string(for:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/yeofr\/yeofrbridge\/string(for:)","abstract":[],"kind":"symbol","role":"symbol","title":"string(for:)","type":"topic","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringForReturnCode:"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/string(for:)"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/loadTracker(from:outTracker:error:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTracker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outTracker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"abstract":[{"text":"Load a tracker from an in-memory blob.","type":"text"}],"kind":"symbol","url":"\/documentation\/yeofr\/yeofrbridge\/loadtracker(from:outtracker:error:)","role":"symbol","title":"loadTracker(from:outTracker:error:)","type":"topic","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"loadTrackerFromData:outTracker:error:"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/loadTracker(from:outTracker:error:)"},"doc://com.youreyeonly.yeofr.YEOFR/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/objc(cs)NSObject"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/learnCurrentFace(_:error:)":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"learnCurrentFace:error:"}],"url":"\/documentation\/yeofr\/yeofrbridge\/learncurrentface(_:error:)","abstract":[{"type":"text","text":"Learn\/improve the current face template (optional helper)."}],"title":"learnCurrentFace(_:error:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"learnCurrentFace","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSErrorPointer","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/learnCurrentFace(_:error:)","kind":"symbol","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/s23CustomStringConvertibleP"},"doc://com.youreyeonly.yeofr.YEOFR/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/s7CVarArgP"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/getTrackerData(_:outData:error:)":{"abstract":[{"type":"text","text":"Get the current tracker as an in-memory blob."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getTrackerData(_:outData:error:)","title":"getTrackerData(_:outData:error:)","url":"\/documentation\/yeofr\/yeofrbridge\/gettrackerdata(_:outdata:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTrackerData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"outData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":"?>?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"text":") -> ","kind":"text"},{"text":"FRSDKReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"getTrackerData:outData:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/objc(pl)NSObject"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)":{"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setTrackerParameters:paramsUTF8:outErrorPosition:error:"}],"url":"\/documentation\/yeofr\/yeofrbridge\/settrackerparameters(_:paramsutf8:outerrorposition:error:)","abstract":[{"text":"Apply tracker parameters from an FRSDK-formatted parameter string.","type":"text"}],"title":"setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTrackerParameters"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paramsUTF8"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outErrorPosition"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","kind":"typeIdentifier","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier","text":"FRSDKReturnCode"}],"type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/configure(withThreads:internalResizeWidth:detectionThreshold:error:)":{"kind":"symbol","role":"symbol","abstract":[{"text":"Configure global SDK parameters.","type":"text"}],"type":"topic","title":"configure(withThreads:internalResizeWidth:detectionThreshold:error:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withThreads","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"internalResizeWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSErrorPointer","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"text":") -> ","kind":"text"},{"text":"FRSDKReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"url":"\/documentation\/yeofr\/yeofrbridge\/configure(withthreads:internalresizewidth:detectionthreshold:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configure(withThreads:internalResizeWidth:detectionThreshold:error:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"configureWithThreads:internalResizeWidth:detectionThreshold:error:","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/detectFaces(inPNGData:tracker:outDetectedCount:error:)":{"title":"detectFaces(inPNGData:tracker:outDetectedCount:error:)","role":"symbol","url":"\/documentation\/yeofr\/yeofrbridge\/detectfaces(inpngdata:tracker:outdetectedcount:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/detectFaces(inPNGData:tracker:outDetectedCount:error:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectFaces"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inPNGData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outDetectedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"abstract":[{"type":"text","text":"Detect faces in a PNG buffer (ARGB is handled internally by the SDK)."}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"detectFacesInPNGData:tracker:outDetectedCount:error:"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/clearTracker(_:error:)":{"title":"clearTracker(_:error:)","role":"symbol","url":"\/documentation\/yeofr\/yeofrbridge\/cleartracker(_:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/clearTracker(_:error:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearTracker"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"abstract":[{"type":"text","text":"Clear tracker."}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearTracker:error:"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/s28CustomDebugStringConvertibleP"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/configure(withThreads:error:)":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configure(withThreads:error:)","url":"\/documentation\/yeofr\/yeofrbridge\/configure(withthreads:error:)","title":"configure(withThreads:error:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withThreads","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"configureWithThreads:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/createTracker(_:error:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Create a new tracker."}],"type":"topic","title":"createTracker(_:error:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTracker"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/createTracker(_:error:)","url":"\/documentation\/yeofr\/yeofrbridge\/createtracker(_:error:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTracker:error:"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/checkPNGImageMatchesTracker(_:tracker:outIsSingle:error:)":{"abstract":[{"text":"Convenience: returns YES iff exactly one face is detected in the PNG.","type":"text"},{"text":" ","type":"text"},{"text":"Same pipeline as above. Useful for “does this match the tracker?” checks.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/checkPNGImageMatchesTracker(_:tracker:outIsSingle:error:)","title":"checkPNGImageMatchesTracker(_:tracker:outIsSingle:error:)","url":"\/documentation\/yeofr\/yeofrbridge\/checkpngimagematchestracker(_:tracker:outissingle:error:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkPNGImageMatchesTracker"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outIsSingle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ObjCBool","preciseIdentifier":"s:10ObjectiveC8ObjCBoolV"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkPNGImageMatchesTracker:tracker:outIsSingle:error:"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRBridge/getHardwareID(_:error:)":{"kind":"symbol","role":"symbol","abstract":[{"text":"Get a device hardware identifier from the SDK (smoke test).","type":"text"}],"type":"topic","title":"getHardwareID(_:error:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getHardwareID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14NSErrorPointera","text":"NSErrorPointer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode"}],"url":"\/documentation\/yeofr\/yeofrbridge\/gethardwareid(_:error:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getHardwareID(_:error:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getHardwareID:error:"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"YEOFRBridge","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"YEOFRBridge","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"YEOFRBridge","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/activate(withKey:dataPath:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/checkPNGImageMatchesTracker(_:tracker:outIsSingle:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/clearTracker(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configure(withThreads:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configure(withThreads:internalResizeWidth:detectionThreshold:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/configureShoulderSurfing(withResizeWidth:detectionThreshold:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/createTracker(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/detectFaces(inPNGData:tracker:outDetectedCount:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/freeTracker(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getHardwareID(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getLicenseInfo(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/getTrackerData(_:outData:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/learnCurrentFace(_:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/loadTracker(from:outTracker:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/setName(_:faceID:name:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRBridge\/string(for:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRBridge","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"setName:faceID:name:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1setName(_:faceID:name:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"setName:faceID:name:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1setName(_:faceID:name:error:)\/fragments"},{"value":"getLicenseInfo:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getLicenseInfo(_:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"getLicenseInfo:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getLicenseInfo(_:error:)\/fragments"},{"value":"configureShoulderSurfingWithResizeWidth:detectionThreshold:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1configureShoulderSurfing(withResizeWidth:detectionThreshold:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"configureShoulderSurfingWithResizeWidth:detectionThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1configureShoulderSurfing(withResizeWidth:detectionThreshold:error:)\/fragments"},{"value":"freeTracker:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1freeTracker(_:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"freeTracker:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1freeTracker(_:error:)\/fragments"},{"value":"YEOFRBridge","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/title"},{"value":[{"text":"YEOFRBridge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/fragments"},{"value":[{"text":"YEOFRBridge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge\/navigatorTitle"},{"value":"activateWithKey:dataPath:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1activate(withKey:dataPath:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"activateWithKey:dataPath:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1activate(withKey:dataPath:error:)\/fragments"},{"value":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"processFrameWithBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1processFrame(withBuffer:width:height:scanLine:tracker:needFaceRect:ratio:outIDs:outNames:outRects:outDetectedCount:error:)\/fragments"},{"value":"stringForReturnCode:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1string(for:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"stringForReturnCode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1string(for:)\/fragments"},{"value":"loadTrackerFromData:outTracker:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1loadTracker(from:outTracker:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"loadTrackerFromData:outTracker:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1loadTracker(from:outTracker:error:)\/fragments"},{"value":"learnCurrentFace:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1learnCurrentFace(_:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"learnCurrentFace:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1learnCurrentFace(_:error:)\/fragments"},{"value":"getTrackerData:outData:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getTrackerData(_:outData:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"getTrackerData:outData:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getTrackerData(_:outData:error:)\/fragments"},{"value":"setTrackerParameters:paramsUTF8:outErrorPosition:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"setTrackerParameters:paramsUTF8:outErrorPosition:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1setTrackerParameters(_:paramsUTF8:outErrorPosition:error:)\/fragments"},{"value":"configureWithThreads:internalResizeWidth:detectionThreshold:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1configure(withThreads:internalResizeWidth:detectionThreshold:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"configureWithThreads:internalResizeWidth:detectionThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1configure(withThreads:internalResizeWidth:detectionThreshold:error:)\/fragments"},{"value":"detectFacesInPNGData:tracker:outDetectedCount:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1detectFaces(inPNGData:tracker:outDetectedCount:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"detectFacesInPNGData:tracker:outDetectedCount:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1detectFaces(inPNGData:tracker:outDetectedCount:error:)\/fragments"},{"value":"clearTracker:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1clearTracker(_:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"clearTracker:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1clearTracker(_:error:)\/fragments"},{"value":"configureWithThreads:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1configure(withThreads:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"configureWithThreads:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1configure(withThreads:error:)\/fragments"},{"value":"createTracker:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1createTracker(_:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"createTracker:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1createTracker(_:error:)\/fragments"},{"value":"checkPNGImageMatchesTracker:tracker:outIsSingle:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1checkPNGImageMatchesTracker(_:tracker:outIsSingle:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"checkPNGImageMatchesTracker:tracker:outIsSingle:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1checkPNGImageMatchesTracker(_:tracker:outIsSingle:error:)\/fragments"},{"value":"getHardwareID:error:","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getHardwareID(_:error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"getHardwareID:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1YEOFRBridge~1getHardwareID(_:error:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}