{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/yeofrsdk\/freetracker()"]}],"seeAlsoSections":[{"anchor":"Tracker-Lifecycle","title":"Tracker Lifecycle","generated":true,"identifiers":["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/createTracker()","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/setTrackerHandle(_:)","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/getTrackerHandle()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Frees the current tracker (if any) and clears the handle.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"freeTracker","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode","kind":"typeIdentifier","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"FRSDKReturnCode","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/freeTracker()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"freeTracker()","modules":[{"name":"YEOFR"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"freeTracker"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode"}],"symbolKind":"method","externalID":"s:5YEOFR8YEOFRSDKC11freeTrackerSo15FRSDKReturnCodeVyF"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK"]]},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK/setTrackerHandle(_:)":{"abstract":[{"text":"Sets (replaces) the current tracker handle.","type":"text"}],"url":"\/documentation\/yeofr\/yeofrsdk\/settrackerhandle(_:)","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/setTrackerHandle(_:)","title":"setTrackerHandle(_:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTrackerHandle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"YEOFRTrackerHandle","preciseIdentifier":"s:5YEOFR18YEOFRTrackerHandlea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK/createTracker()":{"role":"symbol","url":"\/documentation\/yeofr\/yeofrsdk\/createtracker()","title":"createTracker()","abstract":[{"text":"Creates a new tracker and installs it as the current handle.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createTracker","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/createTracker()"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"text":"A device-only face recognition SDK for iOS.","type":"text"}],"role":"collection","type":"topic","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK/getTrackerHandle()":{"abstract":[{"text":"Returns the current tracker handle.","type":"text"}],"url":"\/documentation\/yeofr\/yeofrsdk\/gettrackerhandle()","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/getTrackerHandle()","title":"getTrackerHandle()","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTrackerHandle","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"YEOFRTrackerHandle","preciseIdentifier":"s:5YEOFR18YEOFRTrackerHandlea","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK/freeTracker()":{"role":"symbol","url":"\/documentation\/yeofr\/yeofrsdk\/freetracker()","title":"freeTracker()","abstract":[{"text":"Frees the current tracker (if any) and clears the handle.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"freeTracker","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/freeTracker()"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK":{"role":"symbol","url":"\/documentation\/yeofr\/yeofrsdk","navigatorTitle":[{"text":"YEOFRSDK","kind":"identifier"}],"title":"YEOFRSDK","abstract":[{"text":"YEOFR main entry point.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRSDK","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"title":"FRSDKReturnCode","abstract":[],"url":"\/documentation\/yeofr\/frsdkreturncode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRSDKReturnCode"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"FRSDKReturnCode","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}