{"kind":"symbol","identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/loadTracker(from:)-56yah","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK"]]},"sections":[],"variants":[{"paths":["\/documentation\/yeofr\/yeofrsdk\/loadtracker(from:)-56yah"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") -> ","kind":"text"},{"text":"FRSDKReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Data"},{"type":"text","text":" previously obtained from "},{"type":"codeVoice","code":"faceRecognitionTrackerData()"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"data"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"FRSDKReturnCode"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"items":[{"content":[{"inlineContent":[{"text":"Discussion: Frees any existing tracker before installing the new handle. Also reapplies","type":"text"},{"text":" ","type":"text"},{"text":"current configuration via ","type":"text"},{"code":"resetTrackerParameters()","type":"codeVoice"},{"text":" to ensure consistency.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"abstract":[{"text":"Replaces the current tracker with one loaded from an in-memory blob.","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode","kind":"typeIdentifier"}],"modules":[{"name":"YEOFR"}],"title":"loadTracker(from:)","symbolKind":"method","roleHeading":"Instance Method","externalID":"s:5YEOFR8YEOFRSDKC11loadTracker4fromSo15FRSDKReturnCodeV10Foundation4DataV_tF","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"text":"A device-only face recognition SDK for iOS.","type":"text"}],"role":"collection","type":"topic","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK":{"role":"symbol","url":"\/documentation\/yeofr\/yeofrsdk","navigatorTitle":[{"text":"YEOFRSDK","kind":"identifier"}],"title":"YEOFRSDK","abstract":[{"text":"YEOFR main entry point.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRSDK","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"title":"FRSDKReturnCode","abstract":[],"url":"\/documentation\/yeofr\/frsdkreturncode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRSDKReturnCode"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK/loadTracker(from:)-56yah":{"title":"loadTracker(from:)","abstract":[{"type":"text","text":"Replaces the current tracker with one loaded from an in-memory blob."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/yeofr\/yeofrsdk\/loadtracker(from:)-56yah","kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/loadTracker(from:)-56yah"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","op":"replace","value":"FRSDKReturnCode"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]}]}]}