{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/yeofrsdk\/loadtracker(from:)-12caa"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Decrypts "},{"code":"blob","type":"codeVoice"},{"type":"text","text":" via "},{"type":"codeVoice","code":"config.cryptor"},{"type":"text","text":" and replaces the current"},{"type":"text","text":" "},{"type":"text","text":"tracker with the result. Throws if the cryptor rejects the blob"},{"text":" ","type":"text"},{"text":"(wrong key, tampered ciphertext, algorithm mismatch).","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTracker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"blob"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EncryptedBlob","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/EncryptedBlob","preciseIdentifier":"s:5YEOFR13EncryptedBlobV"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"FRSDKReturnCode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK"]]},"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/loadTracker(from:)-12caa","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","externalID":"s:5YEOFR8YEOFRSDKC11loadTracker4fromSo15FRSDKReturnCodeVAA13EncryptedBlobV_tKF","title":"loadTracker(from:)","symbolKind":"method","modules":[{"name":"YEOFR"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5YEOFR13EncryptedBlobV","text":"EncryptedBlob","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode","kind":"typeIdentifier"}],"role":"symbol"},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK":{"role":"symbol","url":"\/documentation\/yeofr\/yeofrsdk","navigatorTitle":[{"text":"YEOFRSDK","kind":"identifier"}],"title":"YEOFRSDK","abstract":[{"text":"YEOFR main entry point.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRSDK","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK/loadTracker(from:)-12caa":{"role":"symbol","url":"\/documentation\/yeofr\/yeofrsdk\/loadtracker(from:)-12caa","title":"loadTracker(from:)","abstract":[{"text":"Decrypts ","type":"text"},{"code":"blob","type":"codeVoice"},{"text":" via ","type":"text"},{"code":"config.cryptor","type":"codeVoice"},{"text":" and replaces the current","type":"text"},{"text":" ","type":"text"},{"text":"tracker with the result. Throws if the cryptor rejects the blob","type":"text"},{"text":" ","type":"text"},{"text":"(wrong key, tampered ciphertext, algorithm mismatch).","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadTracker","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EncryptedBlob","preciseIdentifier":"s:5YEOFR13EncryptedBlobV","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/loadTracker(from:)-12caa"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"text":"A device-only face recognition SDK for iOS.","type":"text"}],"role":"collection","type":"topic","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/EncryptedBlob":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EncryptedBlob","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/EncryptedBlob","kind":"symbol","navigatorTitle":[{"text":"EncryptedBlob","kind":"identifier"}],"title":"EncryptedBlob","abstract":[{"text":"Versioned envelope around a cryptor’s payload. The ","type":"text"},{"code":"serialized()","type":"codeVoice"},{"text":" ","type":"text"},{"text":"representation is what gets persisted or sent over the wire; the","type":"text"},{"text":" ","type":"text"},{"text":"in-memory form is what the SDK passes to \/ receives from a","type":"text"},{"text":" ","type":"text"},{"code":"Cryptor","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/yeofr\/encryptedblob","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"title":"FRSDKReturnCode","abstract":[],"url":"\/documentation\/yeofr\/frsdkreturncode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRSDKReturnCode"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"FRSDKReturnCode","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","value":[{"text":"FRSDKReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","value":[{"text":"FRSDKReturnCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}