{"variants":[{"paths":["\/documentation\/yeofr\/yeofrsdk\/resettrackerparameters()"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/resetTrackerParameters()"},"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetTrackerParameters"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"FRSDKReturnCode","type":"text"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This wraps the vendor API that takes a single parameter string; a non-zero"},{"type":"text","text":" "},{"type":"text","text":"error position indicates a malformed parameter at a specific offset."}]}],"style":"note","type":"aside","name":"Note"}]}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetTrackerParameters"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@FRSDKReturnCode","text":"FRSDKReturnCode"}],"title":"resetTrackerParameters()","externalID":"s:5YEOFR8YEOFRSDKC22resetTrackerParametersSo15FRSDKReturnCodeVyF","roleHeading":"Instance Method","modules":[{"name":"YEOFR"}]},"kind":"symbol","abstract":[{"text":"Applies the current ","type":"text"},{"code":"config","type":"codeVoice"},{"text":" to the active tracker.","type":"text"}],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK/resetTrackerParameters()":{"kind":"symbol","role":"symbol","title":"resetTrackerParameters()","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK\/resetTrackerParameters()","type":"topic","url":"\/documentation\/yeofr\/yeofrsdk\/resettrackerparameters()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetTrackerParameters","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"FRSDKReturnCode","preciseIdentifier":"c:@E@FRSDKReturnCode","kind":"typeIdentifier"}],"abstract":[{"text":"Applies the current ","type":"text"},{"type":"codeVoice","code":"config"},{"text":" to the active tracker.","type":"text"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"type":"topic","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"url":"\/documentation\/yeofr","title":"YEOFR","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/YEOFRSDK":{"navigatorTitle":[{"text":"YEOFRSDK","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"YEOFR main entry point (singleton)."}],"url":"\/documentation\/yeofr\/yeofrsdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"YEOFRSDK","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/YEOFRSDK","role":"symbol","type":"topic","title":"YEOFRSDK"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frsdkreturncode","abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","kind":"symbol","title":"FRSDKReturnCode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"FRSDKReturnCode","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"FRSDKReturnCode"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"FRSDKReturnCode"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","op":"replace"}]}]}