{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributeNotDetected"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/attributeNotDetected","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/attributenotdetected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/attributenotdetected"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"case","title":"FRBridgeReturnCode.attributeNotDetected","modules":[{"name":"YEOFR"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"attributeNotDetected","kind":"identifier"}],"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeAttributeNotDetected","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"FRBridgeReturnCodeAttributeNotDetected","kind":"identifier"}]},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/yeofr","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"title":"YEOFR","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/attributeNotDetected":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/attributeNotDetected","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributeNotDetected","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode\/attributenotdetected","navigatorTitle":[{"text":"FRBridgeReturnCodeAttributeNotDetected","kind":"identifier"}],"role":"symbol","title":"FRBridgeReturnCode.attributeNotDetected"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"role":"symbol","title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol","type":"topic","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"FRBridgeReturnCodeAttributeNotDetected"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"FRBridgeReturnCodeAttributeNotDetected","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"FRBridgeReturnCodeAttributeNotDetected","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1attributeNotDetected\/title","value":"FRBridgeReturnCodeAttributeNotDetected","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1attributeNotDetected\/fragments","value":[{"text":"FRBridgeReturnCodeAttributeNotDetected","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}