{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/badFileFormat","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/badfileformat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/badfileformat"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badFileFormat","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"FRBridgeReturnCodeBadFileFormat","kind":"identifier"}],"title":"FRBridgeReturnCode.badFileFormat","role":"symbol","modules":[{"name":"YEOFR"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badFileFormat","kind":"identifier"}],"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeBadFileFormat","symbolKind":"case","roleHeading":"Case"},"kind":"symbol","references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/badFileFormat":{"title":"FRBridgeReturnCode.badFileFormat","role":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/badFileFormat","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badFileFormat"}],"kind":"symbol","abstract":[],"url":"\/documentation\/yeofr\/frbridgereturncode\/badfileformat","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeBadFileFormat"}]},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"title":"FRBridgeReturnCode","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"role":"collection","type":"topic","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","title":"YEOFR","url":"\/documentation\/yeofr","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"FRBridgeReturnCodeBadFileFormat","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeBadFileFormat"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"FRBridgeReturnCodeBadFileFormat"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1badFileFormat\/title","value":"FRBridgeReturnCodeBadFileFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1badFileFormat\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCodeBadFileFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]}]}]}