{"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/buffersizeinvalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frbridgereturncode\/buffersizeinvalid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/bufferSizeInvalid","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeBufferSizeInvalid","symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferSizeInvalid"}],"title":"FRBridgeReturnCode.bufferSizeInvalid","navigatorTitle":[{"text":"FRBridgeReturnCodeBufferSizeInvalid","kind":"identifier"}],"modules":[{"name":"YEOFR"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bufferSizeInvalid","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"type":"topic","abstract":[],"title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/bufferSizeInvalid":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeBufferSizeInvalid"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferSizeInvalid"}],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/bufferSizeInvalid","abstract":[],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/buffersizeinvalid","title":"FRBridgeReturnCode.bufferSizeInvalid"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"title":"YEOFR","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"type":"topic","url":"\/documentation\/yeofr"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FRBridgeReturnCodeBufferSizeInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"FRBridgeReturnCodeBufferSizeInvalid","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"FRBridgeReturnCodeBufferSizeInvalid","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"FRBridgeReturnCode","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","op":"replace"},{"value":"FRBridgeReturnCodeBufferSizeInvalid","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1bufferSizeInvalid\/title","op":"replace"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeBufferSizeInvalid"}],"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1bufferSizeInvalid\/fragments","op":"replace"}]}]}