{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/cameraindexdoesnotexist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frbridgereturncode\/cameraindexdoesnotexist"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIndexDoesNotExist"}],"title":"FRBridgeReturnCode.cameraIndexDoesNotExist","modules":[{"name":"YEOFR"}],"navigatorTitle":[{"text":"FRBridgeReturnCodeCameraIndexDoesNotExist","kind":"identifier"}],"role":"symbol","symbolKind":"case","externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeCameraIndexDoesNotExist"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraIndexDoesNotExist","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cameraIndexDoesNotExist","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"type":"topic","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"title":"YEOFR","url":"\/documentation\/yeofr","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"type":"topic","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode","title":"FRBridgeReturnCode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRBridgeReturnCode"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/cameraIndexDoesNotExist":{"kind":"symbol","navigatorTitle":[{"text":"FRBridgeReturnCodeCameraIndexDoesNotExist","kind":"identifier"}],"type":"topic","abstract":[],"title":"FRBridgeReturnCode.cameraIndexDoesNotExist","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraIndexDoesNotExist","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cameraIndexDoesNotExist","url":"\/documentation\/yeofr\/frbridgereturncode\/cameraindexdoesnotexist","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"FRBridgeReturnCodeCameraIndexDoesNotExist","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"FRBridgeReturnCodeCameraIndexDoesNotExist","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"FRBridgeReturnCodeCameraIndexDoesNotExist","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","op":"replace","value":"FRBridgeReturnCode"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","op":"replace","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cameraIndexDoesNotExist\/title","op":"replace","value":"FRBridgeReturnCodeCameraIndexDoesNotExist"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cameraIndexDoesNotExist\/fragments","op":"replace","value":[{"text":"FRBridgeReturnCodeCameraIndexDoesNotExist","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}