{"kind":"symbol","identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cannotOpenFile","interfaceLanguage":"swift"},"metadata":{"title":"FRBridgeReturnCode.cannotOpenFile","symbolKind":"case","externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeCannotOpenFile","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotOpenFile","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeCannotOpenFile"}],"modules":[{"name":"YEOFR"}],"roleHeading":"Case","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotOpenFile"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/cannotopenfile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frbridgereturncode\/cannotopenfile"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"title":"FRBridgeReturnCode","kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRBridgeReturnCode"}],"navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/cannotOpenFile":{"title":"FRBridgeReturnCode.cannotOpenFile","kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/cannotOpenFile","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode\/cannotopenfile","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotOpenFile"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeCannotOpenFile"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"FRBridgeReturnCodeCannotOpenFile","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeCannotOpenFile"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"FRBridgeReturnCodeCannotOpenFile"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"FRBridgeReturnCode","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle"},{"value":"FRBridgeReturnCodeCannotOpenFile","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cannotOpenFile\/title"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeCannotOpenFile"}],"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1cannotOpenFile\/fragments"}]}]}