{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/connectionclosed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/connectionclosed"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeConnectionClosed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionClosed","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"FRBridgeReturnCodeConnectionClosed","kind":"identifier"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"YEOFR"}],"title":"FRBridgeReturnCode.connectionClosed"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionClosed"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionClosed","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"type":"topic","abstract":[],"title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/connectionClosed":{"title":"FRBridgeReturnCode.connectionClosed","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeConnectionClosed"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionClosed"}],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionClosed","abstract":[],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/connectionclosed","type":"topic"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"title":"YEOFR","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"type":"topic","url":"\/documentation\/yeofr"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"FRBridgeReturnCodeConnectionClosed"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCodeConnectionClosed"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"FRBridgeReturnCodeConnectionClosed","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode","op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1connectionClosed\/title","value":"FRBridgeReturnCodeConnectionClosed"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1connectionClosed\/fragments","value":[{"text":"FRBridgeReturnCodeConnectionClosed","kind":"identifier"}]}]}]}