{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectionFailed","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"kind":"symbol","metadata":{"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeConnectionFailed","title":"FRBridgeReturnCode.connectionFailed","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeConnectionFailed"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionFailed"}],"role":"symbol","modules":[{"name":"YEOFR"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/connectionfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/connectionfailed"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionFailed"},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"role":"symbol","title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol","type":"topic","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/connectionFailed":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectionFailed"}],"kind":"symbol","type":"topic","title":"FRBridgeReturnCode.connectionFailed","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeConnectionFailed"}],"abstract":[],"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/connectionFailed","url":"\/documentation\/yeofr\/frbridgereturncode\/connectionfailed"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","url":"\/documentation\/yeofr","kind":"symbol","type":"topic","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"title":"YEOFR","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"FRBridgeReturnCodeConnectionFailed","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"FRBridgeReturnCodeConnectionFailed","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"FRBridgeReturnCodeConnectionFailed"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode","op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1connectionFailed\/title","op":"replace","value":"FRBridgeReturnCodeConnectionFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1connectionFailed\/fragments","value":[{"text":"FRBridgeReturnCodeConnectionFailed","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}