{"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"sections":[],"metadata":{"title":"FRBridgeReturnCode.emptyTrackerData","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emptyTrackerData","kind":"identifier"}],"role":"symbol","modules":[{"name":"YEOFR"}],"navigatorTitle":[{"text":"FRBridgeReturnCodeEmptyTrackerData","kind":"identifier"}],"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeEmptyTrackerData"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyTrackerData"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/emptytrackerdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/emptytrackerdata"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/emptyTrackerData","interfaceLanguage":"swift"},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"role":"collection","type":"topic","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","title":"YEOFR","url":"\/documentation\/yeofr","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"title":"FRBridgeReturnCode","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/emptyTrackerData":{"title":"FRBridgeReturnCode.emptyTrackerData","role":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/emptyTrackerData","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emptyTrackerData","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/emptytrackerdata","navigatorTitle":[{"text":"FRBridgeReturnCodeEmptyTrackerData","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FRBridgeReturnCodeEmptyTrackerData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCodeEmptyTrackerData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"FRBridgeReturnCodeEmptyTrackerData","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1emptyTrackerData\/title","value":"FRBridgeReturnCodeEmptyTrackerData"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1emptyTrackerData\/fragments","value":[{"text":"FRBridgeReturnCodeEmptyTrackerData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}