{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"needServerActivation","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"metadata":{"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"needServerActivation","kind":"identifier"}],"symbolKind":"case","title":"FRBridgeReturnCode.needServerActivation","modules":[{"name":"YEOFR"}],"navigatorTitle":[{"text":"FRBridgeReturnCodeNeedServerActivation","kind":"identifier"}],"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeNeedServerActivation"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/needserveractivation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frbridgereturncode\/needserveractivation"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/needServerActivation"},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/needServerActivation":{"title":"FRBridgeReturnCode.needServerActivation","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"needServerActivation"}],"url":"\/documentation\/yeofr\/frbridgereturncode\/needserveractivation","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeNeedServerActivation"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/needServerActivation"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"role":"symbol","title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol","type":"topic","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","url":"\/documentation\/yeofr","kind":"symbol","type":"topic","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"title":"YEOFR","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FRBridgeReturnCodeNeedServerActivation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCodeNeedServerActivation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"FRBridgeReturnCodeNeedServerActivation","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1needServerActivation\/title","value":"FRBridgeReturnCodeNeedServerActivation"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1needServerActivation\/fragments","value":[{"text":"FRBridgeReturnCodeNeedServerActivation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}