{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/OK","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/ok"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frbridgereturncode\/ok"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OK","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"YEOFR"}],"symbolKind":"case","title":"FRBridgeReturnCode.OK","roleHeading":"Case","externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeOK","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeOK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OK"}],"role":"symbol"},"kind":"symbol","references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"role":"collection","type":"topic","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","title":"YEOFR","url":"\/documentation\/yeofr","kind":"symbol"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/OK":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeOK"}],"abstract":[],"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/OK","url":"\/documentation\/yeofr\/frbridgereturncode\/ok","title":"FRBridgeReturnCode.OK","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OK","kind":"identifier"}]},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"title":"FRBridgeReturnCode","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"FRBridgeReturnCodeOK","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"FRBridgeReturnCodeOK","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"FRBridgeReturnCodeOK","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1OK\/title","value":"FRBridgeReturnCodeOK"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1OK\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCodeOK"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle"}]}]}