{"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"FRBridgeReturnCodeParameterNotFound","kind":"identifier"}],"title":"FRBridgeReturnCode.parameterNotFound","modules":[{"name":"YEOFR"}],"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeParameterNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"parameterNotFound"}],"roleHeading":"Case","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/parameternotfound"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/parameternotfound"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/parameterNotFound"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parameterNotFound","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","title":"FRBridgeReturnCode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol","title":"YEOFR","url":"\/documentation\/yeofr","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"role":"collection","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/parameterNotFound":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/parameterNotFound","abstract":[],"type":"topic","title":"FRBridgeReturnCode.parameterNotFound","url":"\/documentation\/yeofr\/frbridgereturncode\/parameternotfound","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"parameterNotFound"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeParameterNotFound"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"FRBridgeReturnCodeParameterNotFound","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeParameterNotFound"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"FRBridgeReturnCodeParameterNotFound","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"FRBridgeReturnCode","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","op":"replace"},{"value":"FRBridgeReturnCodeParameterNotFound","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1parameterNotFound\/title","op":"replace"},{"value":[{"kind":"identifier","text":"FRBridgeReturnCodeParameterNotFound"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1parameterNotFound\/fragments","op":"replace"}]}]}