{"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syntaxError","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/syntaxerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frbridgereturncode\/syntaxerror"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"syntaxError"}],"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeSyntaxError","title":"FRBridgeReturnCode.syntaxError","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeSyntaxError"}],"modules":[{"name":"YEOFR"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/syntaxError","interfaceLanguage":"swift"},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"title":"YEOFR","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","kind":"symbol","role":"collection","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"type":"topic","url":"\/documentation\/yeofr"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/syntaxError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeSyntaxError"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"syntaxError"}],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/syntaxError","abstract":[],"role":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode\/syntaxerror","title":"FRBridgeReturnCode.syntaxError"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"type":"topic","abstract":[],"title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"FRBridgeReturnCodeSyntaxError"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCodeSyntaxError"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"FRBridgeReturnCodeSyntaxError"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1syntaxError\/title","op":"replace","value":"FRBridgeReturnCodeSyntaxError"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1syntaxError\/fragments","op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCodeSyntaxError"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","op":"replace","value":"FRBridgeReturnCode"},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]},{"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}