{"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/tensorflownotinitialized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frbridgereturncode\/tensorflownotinitialized"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/tensorflowNotInitialized"},"metadata":{"modules":[{"name":"YEOFR"}],"symbolKind":"case","role":"symbol","title":"FRBridgeReturnCode.tensorflowNotInitialized","roleHeading":"Case","navigatorTitle":[{"text":"FRBridgeReturnCodeTensorflowNotInitialized","kind":"identifier"}],"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeTensorflowNotInitialized","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tensorflowNotInitialized","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tensorflowNotInitialized","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","kind":"symbol","title":"YEOFR","url":"\/documentation\/yeofr","abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"role":"collection","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","title":"FRBridgeReturnCode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/tensorflowNotInitialized":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/tensorflowNotInitialized","abstract":[],"type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode\/tensorflownotinitialized","title":"FRBridgeReturnCode.tensorflowNotInitialized","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tensorflowNotInitialized"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeTensorflowNotInitialized"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FRBridgeReturnCodeTensorflowNotInitialized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"FRBridgeReturnCodeTensorflowNotInitialized","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"identifier","text":"FRBridgeReturnCodeTensorflowNotInitialized"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1tensorflowNotInitialized\/title","value":"FRBridgeReturnCodeTensorflowNotInitialized"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1tensorflowNotInitialized\/fragments","value":[{"text":"FRBridgeReturnCodeTensorflowNotInitialized","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}