{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackerBufferMallocFailed","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerBufferMallocFailed","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/trackerbuffermallocfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frbridgereturncode\/trackerbuffermallocfailed"]}],"metadata":{"symbolKind":"case","modules":[{"name":"YEOFR"}],"title":"FRBridgeReturnCode.trackerBufferMallocFailed","externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeTrackerBufferMallocFailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackerBufferMallocFailed","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeTrackerBufferMallocFailed"}],"roleHeading":"Case","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/yeofr\/frbridgereturncode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"title":"FRBridgeReturnCode","role":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","type":"topic","title":"YEOFR","role":"collection","url":"\/documentation\/yeofr","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/trackerBufferMallocFailed":{"title":"FRBridgeReturnCode.trackerBufferMallocFailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackerBufferMallocFailed","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"FRBridgeReturnCodeTrackerBufferMallocFailed","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/trackerBufferMallocFailed","url":"\/documentation\/yeofr\/frbridgereturncode\/trackerbuffermallocfailed","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FRBridgeReturnCodeTrackerBufferMallocFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"FRBridgeReturnCodeTrackerBufferMallocFailed","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"FRBridgeReturnCodeTrackerBufferMallocFailed","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1trackerBufferMallocFailed\/title","value":"FRBridgeReturnCodeTrackerBufferMallocFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1trackerBufferMallocFailed\/fragments","value":[{"text":"FRBridgeReturnCodeTrackerBufferMallocFailed","kind":"identifier"}]}]}]}