{"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedImageExtension","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedImageExtension","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/unsupportedimageextension"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frbridgereturncode\/unsupportedimageextension"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"FRBridgeReturnCodeUnsupportedImageExtension","kind":"identifier"}],"modules":[{"name":"YEOFR"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedImageExtension"}],"title":"FRBridgeReturnCode.unsupportedImageExtension","symbolKind":"case","externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeUnsupportedImageExtension"},"sections":[],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode","kind":"symbol","title":"FRBridgeReturnCode","role":"symbol","type":"topic","url":"\/documentation\/yeofr\/frbridgereturncode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"abstract":[{"type":"text","text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing."}],"url":"\/documentation\/yeofr","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","title":"YEOFR","kind":"symbol","role":"collection"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRBridgeReturnCode/unsupportedImageExtension":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedImageExtension","navigatorTitle":[{"text":"FRBridgeReturnCodeUnsupportedImageExtension","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedImageExtension","kind":"identifier"}],"type":"topic","title":"FRBridgeReturnCode.unsupportedImageExtension","url":"\/documentation\/yeofr\/frbridgereturncode\/unsupportedimageextension","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"FRBridgeReturnCodeUnsupportedImageExtension","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"FRBridgeReturnCodeUnsupportedImageExtension","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"FRBridgeReturnCodeUnsupportedImageExtension","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title","value":"FRBridgeReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle","value":[{"text":"FRBridgeReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedImageExtension\/title","value":"FRBridgeReturnCodeUnsupportedImageExtension"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedImageExtension\/fragments","value":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedImageExtension"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}