{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedTemplateVersion","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@E@FRBridgeReturnCode@FRBridgeReturnCodeUnsupportedTemplateVersion","title":"FRBridgeReturnCode.unsupportedTemplateVersion","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedTemplateVersion"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedTemplateVersion"}],"modules":[{"name":"YEOFR"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/yeofr\/frbridgereturncode\/unsupportedtemplateversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frbridgereturncode\/unsupportedtemplateversion"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedTemplateVersion","interfaceLanguage":"swift"},"references":{"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode/unsupportedTemplateVersion":{"title":"FRBridgeReturnCode.unsupportedTemplateVersion","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedTemplateVersion"}],"url":"\/documentation\/yeofr\/frbridgereturncode\/unsupportedtemplateversion","navigatorTitle":[{"text":"FRBridgeReturnCodeUnsupportedTemplateVersion","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode\/unsupportedTemplateVersion"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR/FRBridgeReturnCode":{"role":"symbol","title":"FRBridgeReturnCode","navigatorTitle":[{"text":"FRBridgeReturnCode","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRBridgeReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frbridgereturncode","kind":"symbol","type":"topic","identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR\/FRBridgeReturnCode"},"doc://com.yeomessaging.YEOFR/documentation/YEOFR":{"identifier":"doc:\/\/com.yeomessaging.YEOFR\/documentation\/YEOFR","url":"\/documentation\/yeofr","kind":"symbol","type":"topic","abstract":[{"text":"On-device face recognition with fused liveness and TrueDepth anti-spoofing.","type":"text"}],"title":"YEOFR","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"FRBridgeReturnCodeUnsupportedTemplateVersion","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedTemplateVersion"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"FRBridgeReturnCodeUnsupportedTemplateVersion","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"FRBridgeReturnCodeUnsupportedTemplateVersion","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedTemplateVersion\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCodeUnsupportedTemplateVersion"}],"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode~1unsupportedTemplateVersion\/fragments"},{"op":"replace","value":"FRBridgeReturnCode","path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"FRBridgeReturnCode"}],"path":"\/references\/doc:~1~1com.yeomessaging.YEOFR~1documentation~1YEOFR~1FRBridgeReturnCode\/navigatorTitle"}]}]}