{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/badFileFormat"},"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/badfileformat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/badfileformat"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"badFileFormat"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"metadata":{"modules":[{"name":"YEOFR"}],"title":"FRSDKReturnCode.badFileFormat","navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodeBadFileFormat"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badFileFormat"}],"role":"symbol","symbolKind":"case","externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodeBadFileFormat"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/badFileFormat":{"title":"FRSDKReturnCode.badFileFormat","url":"\/documentation\/yeofr\/frsdkreturncode\/badfileformat","abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/badFileFormat","navigatorTitle":[{"text":"FRSDKReturnCodeBadFileFormat","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badFileFormat","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"title":"FRSDKReturnCode","abstract":[],"url":"\/documentation\/yeofr\/frsdkreturncode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRSDKReturnCode"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"text":"A device-only face recognition SDK for iOS.","type":"text"}],"role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"FRSDKReturnCodeBadFileFormat","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"FRSDKReturnCodeBadFileFormat","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"identifier","text":"FRSDKReturnCodeBadFileFormat"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"FRSDKReturnCodeBadFileFormat","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1badFileFormat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCodeBadFileFormat"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1badFileFormat\/fragments"},{"op":"replace","value":"FRSDKReturnCode","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title"},{"op":"replace","value":[{"text":"FRSDKReturnCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments"},{"op":"replace","value":[{"text":"FRSDKReturnCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}