{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/connectionfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/connectionfailed"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/connectionFailed","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","modules":[{"name":"YEOFR"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionFailed","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"FRSDKReturnCodeConnectionFailed","kind":"identifier"}],"title":"FRSDKReturnCode.connectionFailed","role":"symbol","externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodeConnectionFailed"},"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionFailed","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"FRSDKReturnCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","url":"\/documentation\/yeofr\/frsdkreturncode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"type":"topic","title":"YEOFR","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/connectionFailed":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/connectionFailed","title":"FRSDKReturnCode.connectionFailed","url":"\/documentation\/yeofr\/frsdkreturncode\/connectionfailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionFailed","kind":"identifier"}],"navigatorTitle":[{"text":"FRSDKReturnCodeConnectionFailed","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"FRSDKReturnCodeConnectionFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"FRSDKReturnCodeConnectionFailed","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"FRSDKReturnCodeConnectionFailed","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","value":"FRSDKReturnCode","op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","op":"replace","value":[{"text":"FRSDKReturnCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1connectionFailed\/title","op":"replace","value":"FRSDKReturnCodeConnectionFailed"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1connectionFailed\/fragments","op":"replace","value":[{"text":"FRSDKReturnCodeConnectionFailed","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}