{"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/failed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/failed"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodeFailed","symbolKind":"case","title":"FRSDKReturnCode.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"roleHeading":"Case","modules":[{"name":"YEOFR"}],"navigatorTitle":[{"text":"FRSDKReturnCodeFailed","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/failed","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"type":"topic","title":"YEOFR","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/failed":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"FRSDKReturnCode.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/failed","url":"\/documentation\/yeofr\/frsdkreturncode\/failed","navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodeFailed"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"FRSDKReturnCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","url":"\/documentation\/yeofr\/frsdkreturncode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"FRSDKReturnCodeFailed","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"FRSDKReturnCodeFailed","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FRSDKReturnCodeFailed"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1failed\/title","value":"FRSDKReturnCodeFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1failed\/fragments","value":[{"text":"FRSDKReturnCodeFailed","kind":"identifier"}]},{"value":"FRSDKReturnCode","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","value":[{"text":"FRSDKReturnCode","kind":"identifier"}]}]}]}