{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/insufficientTrackerMemoryLimit"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insufficientTrackerMemoryLimit"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/insufficienttrackermemorylimit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/insufficienttrackermemorylimit"]}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"metadata":{"title":"FRSDKReturnCode.insufficientTrackerMemoryLimit","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insufficientTrackerMemoryLimit","kind":"identifier"}],"externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodeInsufficientTrackerMemoryLimit","role":"symbol","roleHeading":"Case","modules":[{"name":"YEOFR"}],"navigatorTitle":[{"text":"FRSDKReturnCodeInsufficientTrackerMemoryLimit","kind":"identifier"}]},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/insufficientTrackerMemoryLimit":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/insufficientTrackerMemoryLimit","type":"topic","kind":"symbol","title":"FRSDKReturnCode.insufficientTrackerMemoryLimit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insufficientTrackerMemoryLimit"}],"url":"\/documentation\/yeofr\/frsdkreturncode\/insufficienttrackermemorylimit","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodeInsufficientTrackerMemoryLimit"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"kind":"symbol","url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"type":"topic","role":"collection"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frsdkreturncode","title":"FRSDKReturnCode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FRSDKReturnCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"FRSDKReturnCodeInsufficientTrackerMemoryLimit","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"FRSDKReturnCodeInsufficientTrackerMemoryLimit","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"FRSDKReturnCodeInsufficientTrackerMemoryLimit","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"FRSDKReturnCodeInsufficientTrackerMemoryLimit","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1insufficientTrackerMemoryLimit\/title","op":"replace"},{"value":[{"text":"FRSDKReturnCodeInsufficientTrackerMemoryLimit","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1insufficientTrackerMemoryLimit\/fragments","op":"replace"},{"value":"FRSDKReturnCode","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","op":"replace"},{"value":[{"text":"FRSDKReturnCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","op":"replace"},{"value":[{"text":"FRSDKReturnCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","op":"replace"}]}]}