{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodeInsufficientBufferSize","title":"FRSDKReturnCode.insufficientBufferSize","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insufficientBufferSize"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodeInsufficientBufferSize"}],"modules":[{"name":"YEOFR"}]},"variants":[{"paths":["\/documentation\/yeofr\/frsdkreturncode\/insufficientbuffersize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frsdkreturncode\/insufficientbuffersize"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insufficientBufferSize"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/insufficientBufferSize"},"sections":[],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"title":"FRSDKReturnCode","abstract":[],"url":"\/documentation\/yeofr\/frsdkreturncode","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FRSDKReturnCode"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/insufficientBufferSize":{"role":"symbol","url":"\/documentation\/yeofr\/frsdkreturncode\/insufficientbuffersize","navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodeInsufficientBufferSize"}],"title":"FRSDKReturnCode.insufficientBufferSize","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insufficientBufferSize"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/insufficientBufferSize"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"text":"A device-only face recognition SDK for iOS.","type":"text"}],"role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"FRSDKReturnCodeInsufficientBufferSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"FRSDKReturnCodeInsufficientBufferSize","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"FRSDKReturnCodeInsufficientBufferSize"}]}]}},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","op":"replace","value":"FRSDKReturnCode"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1insufficientBufferSize\/title","op":"replace","value":"FRSDKReturnCodeInsufficientBufferSize"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1insufficientBufferSize\/fragments","op":"replace","value":[{"text":"FRSDKReturnCodeInsufficientBufferSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}