{"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/invalidTemplate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidTemplate","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/invalidtemplate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/invalidtemplate"]}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"metadata":{"title":"FRSDKReturnCode.invalidTemplate","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidTemplate","kind":"identifier"}],"role":"symbol","externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodeInvalidTemplate","roleHeading":"Case","modules":[{"name":"YEOFR"}],"navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodeInvalidTemplate"}]},"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/invalidTemplate":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/invalidTemplate","type":"topic","title":"FRSDKReturnCode.invalidTemplate","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidTemplate"}],"url":"\/documentation\/yeofr\/frsdkreturncode\/invalidtemplate","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodeInvalidTemplate"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frsdkreturncode","title":"FRSDKReturnCode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FRSDKReturnCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"kind":"symbol","url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FRSDKReturnCodeInvalidTemplate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"FRSDKReturnCodeInvalidTemplate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"FRSDKReturnCodeInvalidTemplate","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1invalidTemplate\/title","value":"FRSDKReturnCodeInvalidTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1invalidTemplate\/fragments","value":[{"text":"FRSDKReturnCodeInvalidTemplate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","value":"FRSDKReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","value":[{"text":"FRSDKReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","value":[{"text":"FRSDKReturnCode","kind":"identifier"}]}]}]}