{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginNoPermission"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","title":"FRSDKReturnCode.pluginNoPermission","modules":[{"name":"YEOFR"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginNoPermission"}],"navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodePluginNoPermission"}],"externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodePluginNoPermission"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/pluginNoPermission"},"variants":[{"paths":["\/documentation\/yeofr\/frsdkreturncode\/pluginnopermission"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frsdkreturncode\/pluginnopermission"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/pluginNoPermission":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/pluginNoPermission","title":"FRSDKReturnCode.pluginNoPermission","url":"\/documentation\/yeofr\/frsdkreturncode\/pluginnopermission","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pluginNoPermission","kind":"identifier"}],"navigatorTitle":[{"text":"FRSDKReturnCodePluginNoPermission","kind":"identifier"}],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"url":"\/documentation\/yeofr","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"type":"topic","title":"YEOFR","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"FRSDKReturnCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","url":"\/documentation\/yeofr\/frsdkreturncode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"FRSDKReturnCodePluginNoPermission","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCodePluginNoPermission"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"FRSDKReturnCodePluginNoPermission","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"FRSDKReturnCodePluginNoPermission","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1pluginNoPermission\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCodePluginNoPermission"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1pluginNoPermission\/fragments"},{"op":"replace","value":"FRSDKReturnCode","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCode"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"FRSDKReturnCode"}],"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}