{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pluginNotLoaded","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pluginNotLoaded"}],"symbolKind":"case","title":"FRSDKReturnCode.pluginNotLoaded","modules":[{"name":"YEOFR"}],"navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodePluginNotLoaded"}],"role":"symbol","externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodePluginNotLoaded"},"variants":[{"paths":["\/documentation\/yeofr\/frsdkreturncode\/pluginnotloaded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frsdkreturncode\/pluginnotloaded"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/pluginNotLoaded","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"type":"topic","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"url":"\/documentation\/yeofr","title":"YEOFR","kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frsdkreturncode","abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","kind":"symbol","title":"FRSDKReturnCode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/pluginNotLoaded":{"title":"FRSDKReturnCode.pluginNotLoaded","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pluginNotLoaded","kind":"identifier"}],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/pluginNotLoaded","type":"topic","navigatorTitle":[{"text":"FRSDKReturnCodePluginNotLoaded","kind":"identifier"}],"url":"\/documentation\/yeofr\/frsdkreturncode\/pluginnotloaded","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"FRSDKReturnCodePluginNotLoaded","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"FRSDKReturnCodePluginNotLoaded"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"FRSDKReturnCodePluginNotLoaded","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"FRSDKReturnCode","op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","value":[{"text":"FRSDKReturnCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1pluginNotLoaded\/title","value":"FRSDKReturnCodePluginNotLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1pluginNotLoaded\/fragments","value":[{"text":"FRSDKReturnCodePluginNotLoaded","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}