{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackerBufferMallocFailed"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/trackerbuffermallocfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/yeofr\/frsdkreturncode\/trackerbuffermallocfailed"]}],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/trackerBufferMallocFailed","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"YEOFR"}],"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"FRSDKReturnCodeTrackerBufferMallocFailed","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"trackerBufferMallocFailed","kind":"identifier"}],"title":"FRSDKReturnCode.trackerBufferMallocFailed","externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodeTrackerBufferMallocFailed"},"sections":[],"kind":"symbol","references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/trackerBufferMallocFailed":{"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/trackerBufferMallocFailed","title":"FRSDKReturnCode.trackerBufferMallocFailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackerBufferMallocFailed","kind":"identifier"}],"navigatorTitle":[{"text":"FRSDKReturnCodeTrackerBufferMallocFailed","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/yeofr\/frsdkreturncode\/trackerbuffermallocfailed","abstract":[],"kind":"symbol"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frsdkreturncode","title":"FRSDKReturnCode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FRSDKReturnCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"kind":"symbol","url":"\/documentation\/yeofr","title":"YEOFR","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FRSDKReturnCodeTrackerBufferMallocFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FRSDKReturnCodeTrackerBufferMallocFailed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"FRSDKReturnCodeTrackerBufferMallocFailed","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1trackerBufferMallocFailed\/title","value":"FRSDKReturnCodeTrackerBufferMallocFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1trackerBufferMallocFailed\/fragments","value":[{"kind":"identifier","text":"FRSDKReturnCodeTrackerBufferMallocFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","value":"FRSDKReturnCode"},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRSDKReturnCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}