{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedImageExtension","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/yeofr\/frsdkreturncode\/unsupportedimageextension"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yeofr\/frsdkreturncode\/unsupportedimageextension"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/unsupportedImageExtension","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"YEOFR"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedImageExtension","kind":"identifier"}],"externalID":"c:@E@FRSDKReturnCode@FRSDKReturnCodeUnsupportedImageExtension","roleHeading":"Case","navigatorTitle":[{"text":"FRSDKReturnCodeUnsupportedImageExtension","kind":"identifier"}],"symbolKind":"case","title":"FRSDKReturnCode.unsupportedImageExtension"},"kind":"symbol","references":{"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FRSDKReturnCode","kind":"identifier"}],"url":"\/documentation\/yeofr\/frsdkreturncode","abstract":[],"identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode","kind":"symbol","title":"FRSDKReturnCode","navigatorTitle":[{"text":"FRSDKReturnCode","kind":"identifier"}],"type":"topic"},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR/FRSDKReturnCode/unsupportedImageExtension":{"title":"FRSDKReturnCode.unsupportedImageExtension","abstract":[],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/yeofr\/frsdkreturncode\/unsupportedimageextension","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR\/FRSDKReturnCode\/unsupportedImageExtension","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedImageExtension"}],"navigatorTitle":[{"kind":"identifier","text":"FRSDKReturnCodeUnsupportedImageExtension"}]},"doc://com.youreyeonly.yeofr.YEOFR/documentation/YEOFR":{"type":"topic","role":"collection","identifier":"doc:\/\/com.youreyeonly.yeofr.YEOFR\/documentation\/YEOFR","abstract":[{"type":"text","text":"A device-only face recognition SDK for iOS."}],"url":"\/documentation\/yeofr","title":"YEOFR","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"FRSDKReturnCodeUnsupportedImageExtension","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FRSDKReturnCodeUnsupportedImageExtension"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"FRSDKReturnCodeUnsupportedImageExtension","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/title","value":"FRSDKReturnCode","op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/fragments","value":[{"kind":"identifier","text":"FRSDKReturnCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode\/navigatorTitle","value":[{"kind":"identifier","text":"FRSDKReturnCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1unsupportedImageExtension\/title","value":"FRSDKReturnCodeUnsupportedImageExtension","op":"replace"},{"path":"\/references\/doc:~1~1com.youreyeonly.yeofr.YEOFR~1documentation~1YEOFR~1FRSDKReturnCode~1unsupportedImageExtension\/fragments","value":[{"kind":"identifier","text":"FRSDKReturnCodeUnsupportedImageExtension"}],"op":"replace"}]}]}